// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="store,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.125000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1481,HLS_SYN_LUT=2465,HLS_VERSION=2019_2}" *)

module store (
        ap_clk,
        ap_rst_n,
        m_axi_data_port_AWVALID,
        m_axi_data_port_AWREADY,
        m_axi_data_port_AWADDR,
        m_axi_data_port_AWID,
        m_axi_data_port_AWLEN,
        m_axi_data_port_AWSIZE,
        m_axi_data_port_AWBURST,
        m_axi_data_port_AWLOCK,
        m_axi_data_port_AWCACHE,
        m_axi_data_port_AWPROT,
        m_axi_data_port_AWQOS,
        m_axi_data_port_AWREGION,
        m_axi_data_port_AWUSER,
        m_axi_data_port_WVALID,
        m_axi_data_port_WREADY,
        m_axi_data_port_WDATA,
        m_axi_data_port_WSTRB,
        m_axi_data_port_WLAST,
        m_axi_data_port_WID,
        m_axi_data_port_WUSER,
        m_axi_data_port_ARVALID,
        m_axi_data_port_ARREADY,
        m_axi_data_port_ARADDR,
        m_axi_data_port_ARID,
        m_axi_data_port_ARLEN,
        m_axi_data_port_ARSIZE,
        m_axi_data_port_ARBURST,
        m_axi_data_port_ARLOCK,
        m_axi_data_port_ARCACHE,
        m_axi_data_port_ARPROT,
        m_axi_data_port_ARQOS,
        m_axi_data_port_ARREGION,
        m_axi_data_port_ARUSER,
        m_axi_data_port_RVALID,
        m_axi_data_port_RREADY,
        m_axi_data_port_RDATA,
        m_axi_data_port_RLAST,
        m_axi_data_port_RID,
        m_axi_data_port_RUSER,
        m_axi_data_port_RRESP,
        m_axi_data_port_BVALID,
        m_axi_data_port_BREADY,
        m_axi_data_port_BRESP,
        m_axi_data_port_BID,
        m_axi_data_port_BUSER,
        store_queue_V_V_TDATA,
        store_queue_V_V_TVALID,
        store_queue_V_V_TREADY,
        g2s_dep_queue_V_TDATA,
        g2s_dep_queue_V_TVALID,
        g2s_dep_queue_V_TREADY,
        s2g_dep_queue_V_TDATA,
        s2g_dep_queue_V_TVALID,
        s2g_dep_queue_V_TREADY,
        out_mem_V_Addr_A,
        out_mem_V_EN_A,
        out_mem_V_WEN_A,
        out_mem_V_Din_A,
        out_mem_V_Dout_A,
        out_mem_V_Clk_A,
        out_mem_V_Rst_A,
        s_axi_CONTROL_BUS_AWVALID,
        s_axi_CONTROL_BUS_AWREADY,
        s_axi_CONTROL_BUS_AWADDR,
        s_axi_CONTROL_BUS_WVALID,
        s_axi_CONTROL_BUS_WREADY,
        s_axi_CONTROL_BUS_WDATA,
        s_axi_CONTROL_BUS_WSTRB,
        s_axi_CONTROL_BUS_ARVALID,
        s_axi_CONTROL_BUS_ARREADY,
        s_axi_CONTROL_BUS_ARADDR,
        s_axi_CONTROL_BUS_RVALID,
        s_axi_CONTROL_BUS_RREADY,
        s_axi_CONTROL_BUS_RDATA,
        s_axi_CONTROL_BUS_RRESP,
        s_axi_CONTROL_BUS_BVALID,
        s_axi_CONTROL_BUS_BREADY,
        s_axi_CONTROL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_pp0_stage0 = 10'd8;
parameter    ap_ST_fsm_state9 = 10'd16;
parameter    ap_ST_fsm_state10 = 10'd32;
parameter    ap_ST_fsm_state11 = 10'd64;
parameter    ap_ST_fsm_state12 = 10'd128;
parameter    ap_ST_fsm_state13 = 10'd256;
parameter    ap_ST_fsm_state14 = 10'd512;
parameter    C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA_PORT_ID_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_PORT_DATA_WIDTH = 64;
parameter    C_M_AXI_DATA_PORT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_WUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_RUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_USER_VALUE = 0;
parameter    C_M_AXI_DATA_PORT_PROT_VALUE = 0;
parameter    C_M_AXI_DATA_PORT_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_DATA_PORT_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_data_port_AWVALID;
input   m_axi_data_port_AWREADY;
output  [C_M_AXI_DATA_PORT_ADDR_WIDTH - 1:0] m_axi_data_port_AWADDR;
output  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_AWID;
output  [7:0] m_axi_data_port_AWLEN;
output  [2:0] m_axi_data_port_AWSIZE;
output  [1:0] m_axi_data_port_AWBURST;
output  [1:0] m_axi_data_port_AWLOCK;
output  [3:0] m_axi_data_port_AWCACHE;
output  [2:0] m_axi_data_port_AWPROT;
output  [3:0] m_axi_data_port_AWQOS;
output  [3:0] m_axi_data_port_AWREGION;
output  [C_M_AXI_DATA_PORT_AWUSER_WIDTH - 1:0] m_axi_data_port_AWUSER;
output   m_axi_data_port_WVALID;
input   m_axi_data_port_WREADY;
output  [C_M_AXI_DATA_PORT_DATA_WIDTH - 1:0] m_axi_data_port_WDATA;
output  [C_M_AXI_DATA_PORT_WSTRB_WIDTH - 1:0] m_axi_data_port_WSTRB;
output   m_axi_data_port_WLAST;
output  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_WID;
output  [C_M_AXI_DATA_PORT_WUSER_WIDTH - 1:0] m_axi_data_port_WUSER;
output   m_axi_data_port_ARVALID;
input   m_axi_data_port_ARREADY;
output  [C_M_AXI_DATA_PORT_ADDR_WIDTH - 1:0] m_axi_data_port_ARADDR;
output  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_ARID;
output  [7:0] m_axi_data_port_ARLEN;
output  [2:0] m_axi_data_port_ARSIZE;
output  [1:0] m_axi_data_port_ARBURST;
output  [1:0] m_axi_data_port_ARLOCK;
output  [3:0] m_axi_data_port_ARCACHE;
output  [2:0] m_axi_data_port_ARPROT;
output  [3:0] m_axi_data_port_ARQOS;
output  [3:0] m_axi_data_port_ARREGION;
output  [C_M_AXI_DATA_PORT_ARUSER_WIDTH - 1:0] m_axi_data_port_ARUSER;
input   m_axi_data_port_RVALID;
output   m_axi_data_port_RREADY;
input  [C_M_AXI_DATA_PORT_DATA_WIDTH - 1:0] m_axi_data_port_RDATA;
input   m_axi_data_port_RLAST;
input  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_RID;
input  [C_M_AXI_DATA_PORT_RUSER_WIDTH - 1:0] m_axi_data_port_RUSER;
input  [1:0] m_axi_data_port_RRESP;
input   m_axi_data_port_BVALID;
output   m_axi_data_port_BREADY;
input  [1:0] m_axi_data_port_BRESP;
input  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_BID;
input  [C_M_AXI_DATA_PORT_BUSER_WIDTH - 1:0] m_axi_data_port_BUSER;
input  [127:0] store_queue_V_V_TDATA;
input   store_queue_V_V_TVALID;
output   store_queue_V_V_TREADY;
input  [7:0] g2s_dep_queue_V_TDATA;
input   g2s_dep_queue_V_TVALID;
output   g2s_dep_queue_V_TREADY;
output  [7:0] s2g_dep_queue_V_TDATA;
output   s2g_dep_queue_V_TVALID;
input   s2g_dep_queue_V_TREADY;
output  [31:0] out_mem_V_Addr_A;
output   out_mem_V_EN_A;
output  [15:0] out_mem_V_WEN_A;
output  [127:0] out_mem_V_Din_A;
input  [127:0] out_mem_V_Dout_A;
output   out_mem_V_Clk_A;
output   out_mem_V_Rst_A;
input   s_axi_CONTROL_BUS_AWVALID;
output   s_axi_CONTROL_BUS_AWREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR;
input   s_axi_CONTROL_BUS_WVALID;
output   s_axi_CONTROL_BUS_WREADY;
input  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA;
input  [C_S_AXI_CONTROL_BUS_WSTRB_WIDTH - 1:0] s_axi_CONTROL_BUS_WSTRB;
input   s_axi_CONTROL_BUS_ARVALID;
output   s_axi_CONTROL_BUS_ARREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR;
output   s_axi_CONTROL_BUS_RVALID;
input   s_axi_CONTROL_BUS_RREADY;
output  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA;
output  [1:0] s_axi_CONTROL_BUS_RRESP;
output   s_axi_CONTROL_BUS_BVALID;
input   s_axi_CONTROL_BUS_BREADY;
output  [1:0] s_axi_CONTROL_BUS_BRESP;
output   interrupt;

reg store_queue_V_V_TREADY;
reg g2s_dep_queue_V_TREADY;
reg out_mem_V_EN_A;
reg out_mem_V_Rst_A;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] outputs_V;
reg    data_port_blk_n_AW;
wire    ap_CS_fsm_state3;
reg    data_port_blk_n_W;
reg    ap_enable_reg_pp0_iter4;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln543_reg_640;
reg   [0:0] icmp_ln543_reg_640_pp0_iter3_reg;
reg    data_port_blk_n_B;
wire    ap_CS_fsm_state13;
reg    store_queue_V_V_TDATA_blk_n;
reg    g2s_dep_queue_V_TDATA_blk_n;
wire   [0:0] tmp_2_fu_288_p3;
reg    s2g_dep_queue_V_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln538_fu_352_p2;
wire   [0:0] tmp_6_fu_380_p3;
wire    ap_CS_fsm_state14;
reg   [0:0] tmp_6_reg_625;
reg    data_port_AWVALID;
wire    data_port_AWREADY;
wire   [31:0] data_port_AWADDR;
reg    data_port_WVALID;
wire    data_port_WREADY;
wire    data_port_ARREADY;
wire    data_port_RVALID;
wire   [63:0] data_port_RDATA;
wire    data_port_RLAST;
wire   [0:0] data_port_RID;
wire   [0:0] data_port_RUSER;
wire   [1:0] data_port_RRESP;
wire    data_port_BVALID;
reg    data_port_BREADY;
wire   [1:0] data_port_BRESP;
wire   [0:0] data_port_BID;
wire   [0:0] data_port_BUSER;
reg   [16:0] phi_ln543_reg_253;
wire   [33:0] p_cast4_fu_274_p1;
reg   [33:0] p_cast4_reg_564;
reg    ap_block_state1;
reg   [127:0] tmp_V_reg_569;
reg   [15:0] tmp_reg_587;
wire   [15:0] trunc_ln2_fu_326_p4;
reg   [15:0] trunc_ln2_reg_592;
wire   [31:0] zext_ln304_fu_336_p1;
reg   [31:0] zext_ln304_reg_597;
wire   [16:0] and_ln_fu_340_p3;
reg   [16:0] and_ln_reg_602;
wire   [31:0] zext_ln543_fu_348_p1;
reg   [31:0] zext_ln543_reg_607;
wire   [15:0] y_fu_357_p2;
reg   [15:0] y_reg_615;
reg    ap_predicate_op57_write_state2;
reg    ap_block_state2_io;
wire   [33:0] add_ln542_fu_375_p2;
reg   [33:0] add_ln542_reg_620;
wire   [13:0] shl_ln_fu_401_p3;
reg   [13:0] shl_ln_reg_635;
wire   [0:0] icmp_ln543_fu_409_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state8_pp0_stage0_iter4;
reg    ap_block_state8_io;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln543_reg_640_pp0_iter1_reg;
reg   [0:0] icmp_ln543_reg_640_pp0_iter2_reg;
wire   [16:0] add_ln543_fu_414_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] empty_9_fu_444_p1;
reg   [0:0] empty_9_reg_654;
reg   [127:0] out_mem_V_load_reg_659;
wire   [6:0] tmp_8_fu_448_p3;
reg   [6:0] tmp_8_reg_665;
wire   [6:0] empty_10_fu_455_p2;
reg   [6:0] empty_10_reg_670;
wire   [0:0] icmp_ln543_1_fu_461_p2;
reg   [0:0] icmp_ln543_1_reg_675;
wire   [7:0] sub_ln543_2_fu_520_p2;
reg   [7:0] sub_ln543_2_reg_682;
wire   [127:0] lshr_ln543_fu_530_p2;
reg   [127:0] lshr_ln543_reg_687;
wire   [63:0] trunc_ln543_2_fu_550_p1;
reg   [63:0] trunc_ln543_2_reg_692;
wire   [15:0] sram_idx_V_1_fu_554_p2;
reg   [15:0] sram_idx_V_1_reg_697;
wire    ap_CS_fsm_state9;
wire   [31:0] add_ln304_fu_559_p2;
reg   [31:0] add_ln304_reg_702;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [15:0] sram_idx_V_0_reg_222;
reg   [31:0] dram_idx_V_reg_232;
reg   [15:0] y_0_reg_242;
wire   [63:0] zext_ln543_1_fu_439_p1;
wire   [63:0] zext_ln542_fu_387_p1;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] out_mem_V_Addr_A_orig;
wire   [28:0] tmp_1_fu_264_p4;
wire   [15:0] tmp_3_fu_278_p4;
wire   [32:0] ret_V_fu_363_p3;
wire   [33:0] zext_ln1352_fu_371_p1;
wire   [12:0] trunc_ln543_fu_397_p1;
wire   [13:0] trunc_ln543_1_fu_420_p1;
wire   [13:0] add_ln543_1_fu_424_p2;
wire   [12:0] lshr_ln543_1_fu_429_p4;
wire   [7:0] zext_ln543_2_fu_467_p1;
wire   [7:0] zext_ln543_3_fu_470_p1;
wire   [7:0] sub_ln543_fu_482_p2;
wire   [7:0] sub_ln543_1_fu_494_p2;
reg   [127:0] tmp_7_fu_473_p4;
wire   [7:0] xor_ln543_fu_488_p2;
wire   [7:0] select_ln543_fu_500_p3;
wire   [7:0] select_ln543_2_fu_513_p3;
wire   [127:0] select_ln543_1_fu_507_p3;
wire   [127:0] zext_ln543_4_fu_526_p1;
wire   [127:0] zext_ln543_5_fu_536_p1;
wire   [127:0] lshr_ln543_2_fu_539_p2;
wire   [127:0] and_ln543_fu_545_p2;
wire    regslice_both_s2g_dep_queue_V_U_apdone_blk;
reg    ap_block_state14_io;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_store_queue_V_V_U_apdone_blk;
wire   [127:0] store_queue_V_V_TDATA_int;
wire    store_queue_V_V_TVALID_int;
reg    store_queue_V_V_TREADY_int;
wire    regslice_both_store_queue_V_V_U_ack_in;
wire    regslice_both_g2s_dep_queue_V_U_apdone_blk;
wire   [7:0] g2s_dep_queue_V_TDATA_int;
wire    g2s_dep_queue_V_TVALID_int;
reg    g2s_dep_queue_V_TREADY_int;
wire    regslice_both_g2s_dep_queue_V_U_ack_in;
reg    s2g_dep_queue_V_TVALID_int;
wire    s2g_dep_queue_V_TREADY_int;
wire    regslice_both_s2g_dep_queue_V_U_vld_out;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

store_CONTROL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_BUS_DATA_WIDTH ))
store_CONTROL_BUS_s_axi_U(
    .AWVALID(s_axi_CONTROL_BUS_AWVALID),
    .AWREADY(s_axi_CONTROL_BUS_AWREADY),
    .AWADDR(s_axi_CONTROL_BUS_AWADDR),
    .WVALID(s_axi_CONTROL_BUS_WVALID),
    .WREADY(s_axi_CONTROL_BUS_WREADY),
    .WDATA(s_axi_CONTROL_BUS_WDATA),
    .WSTRB(s_axi_CONTROL_BUS_WSTRB),
    .ARVALID(s_axi_CONTROL_BUS_ARVALID),
    .ARREADY(s_axi_CONTROL_BUS_ARREADY),
    .ARADDR(s_axi_CONTROL_BUS_ARADDR),
    .RVALID(s_axi_CONTROL_BUS_RVALID),
    .RREADY(s_axi_CONTROL_BUS_RREADY),
    .RDATA(s_axi_CONTROL_BUS_RDATA),
    .RRESP(s_axi_CONTROL_BUS_RRESP),
    .BVALID(s_axi_CONTROL_BUS_BVALID),
    .BREADY(s_axi_CONTROL_BUS_BREADY),
    .BRESP(s_axi_CONTROL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .outputs_V(outputs_V)
);

store_data_port_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 64 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DATA_PORT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DATA_PORT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DATA_PORT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DATA_PORT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DATA_PORT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DATA_PORT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DATA_PORT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DATA_PORT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_DATA_PORT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DATA_PORT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DATA_PORT_CACHE_VALUE ))
store_data_port_m_axi_U(
    .AWVALID(m_axi_data_port_AWVALID),
    .AWREADY(m_axi_data_port_AWREADY),
    .AWADDR(m_axi_data_port_AWADDR),
    .AWID(m_axi_data_port_AWID),
    .AWLEN(m_axi_data_port_AWLEN),
    .AWSIZE(m_axi_data_port_AWSIZE),
    .AWBURST(m_axi_data_port_AWBURST),
    .AWLOCK(m_axi_data_port_AWLOCK),
    .AWCACHE(m_axi_data_port_AWCACHE),
    .AWPROT(m_axi_data_port_AWPROT),
    .AWQOS(m_axi_data_port_AWQOS),
    .AWREGION(m_axi_data_port_AWREGION),
    .AWUSER(m_axi_data_port_AWUSER),
    .WVALID(m_axi_data_port_WVALID),
    .WREADY(m_axi_data_port_WREADY),
    .WDATA(m_axi_data_port_WDATA),
    .WSTRB(m_axi_data_port_WSTRB),
    .WLAST(m_axi_data_port_WLAST),
    .WID(m_axi_data_port_WID),
    .WUSER(m_axi_data_port_WUSER),
    .ARVALID(m_axi_data_port_ARVALID),
    .ARREADY(m_axi_data_port_ARREADY),
    .ARADDR(m_axi_data_port_ARADDR),
    .ARID(m_axi_data_port_ARID),
    .ARLEN(m_axi_data_port_ARLEN),
    .ARSIZE(m_axi_data_port_ARSIZE),
    .ARBURST(m_axi_data_port_ARBURST),
    .ARLOCK(m_axi_data_port_ARLOCK),
    .ARCACHE(m_axi_data_port_ARCACHE),
    .ARPROT(m_axi_data_port_ARPROT),
    .ARQOS(m_axi_data_port_ARQOS),
    .ARREGION(m_axi_data_port_ARREGION),
    .ARUSER(m_axi_data_port_ARUSER),
    .RVALID(m_axi_data_port_RVALID),
    .RREADY(m_axi_data_port_RREADY),
    .RDATA(m_axi_data_port_RDATA),
    .RLAST(m_axi_data_port_RLAST),
    .RID(m_axi_data_port_RID),
    .RUSER(m_axi_data_port_RUSER),
    .RRESP(m_axi_data_port_RRESP),
    .BVALID(m_axi_data_port_BVALID),
    .BREADY(m_axi_data_port_BREADY),
    .BRESP(m_axi_data_port_BRESP),
    .BID(m_axi_data_port_BID),
    .BUSER(m_axi_data_port_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(data_port_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(data_port_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(data_port_RDATA),
    .I_RID(data_port_RID),
    .I_RUSER(data_port_RUSER),
    .I_RRESP(data_port_RRESP),
    .I_RLAST(data_port_RLAST),
    .I_AWVALID(data_port_AWVALID),
    .I_AWREADY(data_port_AWREADY),
    .I_AWADDR(data_port_AWADDR),
    .I_AWID(1'd0),
    .I_AWLEN(zext_ln543_reg_607),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(data_port_WVALID),
    .I_WREADY(data_port_WREADY),
    .I_WDATA(trunc_ln543_2_reg_692),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(8'd255),
    .I_BVALID(data_port_BVALID),
    .I_BREADY(data_port_BREADY),
    .I_BRESP(data_port_BRESP),
    .I_BID(data_port_BID),
    .I_BUSER(data_port_BUSER)
);

regslice_both #(
    .DataWidth( 128 ))
regslice_both_store_queue_V_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(store_queue_V_V_TDATA),
    .vld_in(store_queue_V_V_TVALID),
    .ack_in(regslice_both_store_queue_V_V_U_ack_in),
    .data_out(store_queue_V_V_TDATA_int),
    .vld_out(store_queue_V_V_TVALID_int),
    .ack_out(store_queue_V_V_TREADY_int),
    .apdone_blk(regslice_both_store_queue_V_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_g2s_dep_queue_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(g2s_dep_queue_V_TDATA),
    .vld_in(g2s_dep_queue_V_TVALID),
    .ack_in(regslice_both_g2s_dep_queue_V_U_ack_in),
    .data_out(g2s_dep_queue_V_TDATA_int),
    .vld_out(g2s_dep_queue_V_TVALID_int),
    .ack_out(g2s_dep_queue_V_TREADY_int),
    .apdone_blk(regslice_both_g2s_dep_queue_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_s2g_dep_queue_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd1),
    .vld_in(s2g_dep_queue_V_TVALID_int),
    .ack_in(s2g_dep_queue_V_TREADY_int),
    .data_out(s2g_dep_queue_V_TDATA),
    .vld_out(regslice_both_s2g_dep_queue_V_U_vld_out),
    .ack_out(s2g_dep_queue_V_TREADY),
    .apdone_blk(regslice_both_s2g_dep_queue_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((data_port_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state4)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state4);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((data_port_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((data_port_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        dram_idx_V_reg_232 <= add_ln304_reg_702;
    end else if ((~((store_queue_V_V_TVALID_int == 1'b0) | (ap_start == 1'b0) | ((g2s_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_288_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1))) begin
        dram_idx_V_reg_232 <= {{store_queue_V_V_TDATA_int[56:25]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln543_fu_409_p2 == 1'd0))) begin
        phi_ln543_reg_253 <= add_ln543_fu_414_p2;
    end else if (((data_port_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_ln543_reg_253 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((data_port_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        sram_idx_V_0_reg_222 <= sram_idx_V_1_reg_697;
    end else if ((~((store_queue_V_V_TVALID_int == 1'b0) | (ap_start == 1'b0) | ((g2s_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_288_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1))) begin
        sram_idx_V_0_reg_222 <= {{store_queue_V_V_TDATA_int[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if (((data_port_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        y_0_reg_242 <= y_reg_615;
    end else if ((~((store_queue_V_V_TVALID_int == 1'b0) | (ap_start == 1'b0) | ((g2s_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_288_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1))) begin
        y_0_reg_242 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln304_reg_702 <= add_ln304_fu_559_p2;
        sram_idx_V_1_reg_697 <= sram_idx_V_1_fu_554_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln538_fu_352_p2 == 1'd0))) begin
        add_ln542_reg_620 <= add_ln542_fu_375_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((store_queue_V_V_TVALID_int == 1'b0) | (ap_start == 1'b0) | ((g2s_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_288_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln_reg_602[16 : 1] <= and_ln_fu_340_p3[16 : 1];
        p_cast4_reg_564[28 : 0] <= p_cast4_fu_274_p1[28 : 0];
        tmp_V_reg_569 <= store_queue_V_V_TDATA_int;
        tmp_reg_587 <= {{store_queue_V_V_TDATA_int[79:64]}};
        trunc_ln2_reg_592 <= {{store_queue_V_V_TDATA_int[95:80]}};
        zext_ln304_reg_597[15 : 0] <= zext_ln304_fu_336_p1[15 : 0];
        zext_ln543_reg_607[16 : 1] <= zext_ln543_fu_348_p1[16 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln543_reg_640 == 1'd0))) begin
        empty_10_reg_670[6] <= empty_10_fu_455_p2[6];
        icmp_ln543_1_reg_675 <= icmp_ln543_1_fu_461_p2;
        out_mem_V_load_reg_659 <= out_mem_V_Dout_A;
        tmp_8_reg_665[6] <= tmp_8_fu_448_p3[6];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln543_fu_409_p2 == 1'd0))) begin
        empty_9_reg_654 <= empty_9_fu_444_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln543_reg_640 <= icmp_ln543_fu_409_p2;
        icmp_ln543_reg_640_pp0_iter1_reg <= icmp_ln543_reg_640;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln543_reg_640_pp0_iter2_reg <= icmp_ln543_reg_640_pp0_iter1_reg;
        icmp_ln543_reg_640_pp0_iter3_reg <= icmp_ln543_reg_640_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln543_reg_640_pp0_iter1_reg == 1'd0))) begin
        lshr_ln543_reg_687 <= lshr_ln543_fu_530_p2;
        sub_ln543_2_reg_682[7 : 1] <= sub_ln543_2_fu_520_p2[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((data_port_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        shl_ln_reg_635[13 : 1] <= shl_ln_fu_401_p3[13 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln538_fu_352_p2 == 1'd1))) begin
        tmp_6_reg_625 <= tmp_V_reg_569[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln543_reg_640_pp0_iter2_reg == 1'd0))) begin
        trunc_ln543_2_reg_692 <= trunc_ln543_2_fu_550_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        y_reg_615 <= y_fu_357_p2;
    end
end

always @ (*) begin
    if ((icmp_ln543_fu_409_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state14_io) | (regslice_both_s2g_dep_queue_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state14_io) | (regslice_both_s2g_dep_queue_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((data_port_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_port_AWVALID = 1'b1;
    end else begin
        data_port_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((data_port_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        data_port_BREADY = 1'b1;
    end else begin
        data_port_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln543_reg_640_pp0_iter3_reg == 1'd0))) begin
        data_port_WVALID = 1'b1;
    end else begin
        data_port_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_port_blk_n_AW = m_axi_data_port_AWREADY;
    end else begin
        data_port_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_port_blk_n_B = m_axi_data_port_BVALID;
    end else begin
        data_port_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln543_reg_640_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_port_blk_n_W = m_axi_data_port_WREADY;
    end else begin
        data_port_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_2_fu_288_p3 == 1'd1))) begin
        g2s_dep_queue_V_TDATA_blk_n = g2s_dep_queue_V_TVALID_int;
    end else begin
        g2s_dep_queue_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((g2s_dep_queue_V_TVALID == 1'b1) & (regslice_both_g2s_dep_queue_V_U_ack_in == 1'b1))) begin
        g2s_dep_queue_V_TREADY = 1'b1;
    end else begin
        g2s_dep_queue_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((store_queue_V_V_TVALID_int == 1'b0) | (ap_start == 1'b0) | ((g2s_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_288_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1) & (tmp_2_fu_288_p3 == 1'd1))) begin
        g2s_dep_queue_V_TREADY_int = 1'b1;
    end else begin
        g2s_dep_queue_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_mem_V_EN_A = 1'b1;
    end else begin
        out_mem_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state14) & (tmp_6_reg_625 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_380_p3 == 1'd1) & (icmp_ln538_fu_352_p2 == 1'd1)))) begin
        s2g_dep_queue_V_TDATA_blk_n = s2g_dep_queue_V_TREADY_int;
    end else begin
        s2g_dep_queue_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (ap_predicate_op57_write_state2 == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        s2g_dep_queue_V_TVALID_int = 1'b1;
    end else begin
        s2g_dep_queue_V_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        store_queue_V_V_TDATA_blk_n = store_queue_V_V_TVALID_int;
    end else begin
        store_queue_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((store_queue_V_V_TVALID == 1'b1) & (regslice_both_store_queue_V_V_U_ack_in == 1'b1))) begin
        store_queue_V_V_TREADY = 1'b1;
    end else begin
        store_queue_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((store_queue_V_V_TVALID_int == 1'b0) | (ap_start == 1'b0) | ((g2s_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_288_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1))) begin
        store_queue_V_V_TREADY_int = 1'b1;
    end else begin
        store_queue_V_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((store_queue_V_V_TVALID_int == 1'b0) | (ap_start == 1'b0) | ((g2s_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_288_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln538_fu_352_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln538_fu_352_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((data_port_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln543_fu_409_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln543_fu_409_p2 == 1'd1)) | ((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((data_port_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if ((~((1'b1 == ap_block_state14_io) | (regslice_both_s2g_dep_queue_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln304_fu_559_p2 = (dram_idx_V_reg_232 + zext_ln304_reg_597);

assign add_ln542_fu_375_p2 = (p_cast4_reg_564 + zext_ln1352_fu_371_p1);

assign add_ln543_1_fu_424_p2 = (shl_ln_reg_635 + trunc_ln543_1_fu_420_p1);

assign add_ln543_fu_414_p2 = (phi_ln543_reg_253 + 17'd1);

assign and_ln543_fu_545_p2 = (lshr_ln543_reg_687 & lshr_ln543_2_fu_539_p2);

assign and_ln_fu_340_p3 = {{trunc_ln2_fu_326_p4}, {1'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((store_queue_V_V_TVALID_int == 1'b0) | (ap_start == 1'b0) | ((g2s_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_288_p3 == 1'd1)));
end

always @ (*) begin
    ap_block_state14_io = ((s2g_dep_queue_V_TREADY_int == 1'b0) & (tmp_6_reg_625 == 1'd1));
end

always @ (*) begin
    ap_block_state2_io = ((s2g_dep_queue_V_TREADY_int == 1'b0) & (ap_predicate_op57_write_state2 == 1'b1));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((data_port_WREADY == 1'b0) & (icmp_ln543_reg_640_pp0_iter3_reg == 1'd0));
end

assign ap_block_state8_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op57_write_state2 = ((tmp_6_fu_380_p3 == 1'd1) & (icmp_ln538_fu_352_p2 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_port_AWADDR = zext_ln542_fu_387_p1;

assign empty_10_fu_455_p2 = (tmp_8_fu_448_p3 | 7'd63);

assign empty_9_fu_444_p1 = phi_ln543_reg_253[0:0];

assign icmp_ln538_fu_352_p2 = ((y_0_reg_242 == tmp_reg_587) ? 1'b1 : 1'b0);

assign icmp_ln543_1_fu_461_p2 = ((tmp_8_fu_448_p3 > empty_10_fu_455_p2) ? 1'b1 : 1'b0);

assign icmp_ln543_fu_409_p2 = ((phi_ln543_reg_253 == and_ln_reg_602) ? 1'b1 : 1'b0);

assign lshr_ln543_1_fu_429_p4 = {{add_ln543_1_fu_424_p2[13:1]}};

assign lshr_ln543_2_fu_539_p2 = 128'd340282366920938463463374607431768211455 >> zext_ln543_5_fu_536_p1;

assign lshr_ln543_fu_530_p2 = select_ln543_1_fu_507_p3 >> zext_ln543_4_fu_526_p1;

assign out_mem_V_Addr_A = out_mem_V_Addr_A_orig << 32'd4;

assign out_mem_V_Addr_A_orig = zext_ln543_1_fu_439_p1;

assign out_mem_V_Clk_A = ap_clk;

assign out_mem_V_Din_A = 128'd0;

always @ (*) begin
    out_mem_V_Rst_A = ~ap_rst_n;
end

assign out_mem_V_WEN_A = 16'd0;

assign p_cast4_fu_274_p1 = tmp_1_fu_264_p4;

assign ret_V_fu_363_p3 = {{dram_idx_V_reg_232}, {1'd0}};

assign s2g_dep_queue_V_TVALID = regslice_both_s2g_dep_queue_V_U_vld_out;

assign select_ln543_1_fu_507_p3 = ((icmp_ln543_1_reg_675[0:0] === 1'b1) ? tmp_7_fu_473_p4 : out_mem_V_load_reg_659);

assign select_ln543_2_fu_513_p3 = ((icmp_ln543_1_reg_675[0:0] === 1'b1) ? xor_ln543_fu_488_p2 : zext_ln543_2_fu_467_p1);

assign select_ln543_fu_500_p3 = ((icmp_ln543_1_reg_675[0:0] === 1'b1) ? sub_ln543_fu_482_p2 : sub_ln543_1_fu_494_p2);

assign shl_ln_fu_401_p3 = {{trunc_ln543_fu_397_p1}, {1'd0}};

assign sram_idx_V_1_fu_554_p2 = (trunc_ln2_reg_592 + sram_idx_V_0_reg_222);

assign sub_ln543_1_fu_494_p2 = (zext_ln543_3_fu_470_p1 - zext_ln543_2_fu_467_p1);

assign sub_ln543_2_fu_520_p2 = (8'd127 - select_ln543_fu_500_p3);

assign sub_ln543_fu_482_p2 = (zext_ln543_2_fu_467_p1 - zext_ln543_3_fu_470_p1);

assign tmp_1_fu_264_p4 = {{outputs_V[31:3]}};

assign tmp_2_fu_288_p3 = store_queue_V_V_TDATA_int[32'd3];

assign tmp_3_fu_278_p4 = {{store_queue_V_V_TDATA_int[111:96]}};

assign tmp_6_fu_380_p3 = tmp_V_reg_569[32'd5];

integer ap_tvar_int_0;

always @ (out_mem_V_load_reg_659) begin
    for (ap_tvar_int_0 = 128 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 127 - 0) begin
            tmp_7_fu_473_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_7_fu_473_p4[ap_tvar_int_0] = out_mem_V_load_reg_659[127 - ap_tvar_int_0];
        end
    end
end

assign tmp_8_fu_448_p3 = {{empty_9_reg_654}, {6'd0}};

assign trunc_ln2_fu_326_p4 = {{store_queue_V_V_TDATA_int[95:80]}};

assign trunc_ln543_1_fu_420_p1 = phi_ln543_reg_253[13:0];

assign trunc_ln543_2_fu_550_p1 = and_ln543_fu_545_p2[63:0];

assign trunc_ln543_fu_397_p1 = sram_idx_V_0_reg_222[12:0];

assign xor_ln543_fu_488_p2 = (zext_ln543_2_fu_467_p1 ^ 8'd127);

assign y_fu_357_p2 = (y_0_reg_242 + 16'd1);

assign zext_ln1352_fu_371_p1 = ret_V_fu_363_p3;

assign zext_ln304_fu_336_p1 = tmp_3_fu_278_p4;

assign zext_ln542_fu_387_p1 = add_ln542_reg_620;

assign zext_ln543_1_fu_439_p1 = lshr_ln543_1_fu_429_p4;

assign zext_ln543_2_fu_467_p1 = tmp_8_reg_665;

assign zext_ln543_3_fu_470_p1 = empty_10_reg_670;

assign zext_ln543_4_fu_526_p1 = select_ln543_2_fu_513_p3;

assign zext_ln543_5_fu_536_p1 = sub_ln543_2_reg_682;

assign zext_ln543_fu_348_p1 = and_ln_fu_340_p3;

always @ (posedge ap_clk) begin
    p_cast4_reg_564[33:29] <= 5'b00000;
    zext_ln304_reg_597[31:16] <= 16'b0000000000000000;
    and_ln_reg_602[0] <= 1'b0;
    zext_ln543_reg_607[0] <= 1'b0;
    zext_ln543_reg_607[31:17] <= 15'b000000000000000;
    shl_ln_reg_635[0] <= 1'b0;
    tmp_8_reg_665[5:0] <= 6'b000000;
    empty_10_reg_670[5:0] <= 6'b111111;
    sub_ln543_2_reg_682[0] <= 1'b0;
end

endmodule //store
