// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="load,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.275000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=4241,HLS_SYN_LUT=18146,HLS_VERSION=2019_2}" *)

module load (
        ap_clk,
        ap_rst_n,
        m_axi_data_port_AWVALID,
        m_axi_data_port_AWREADY,
        m_axi_data_port_AWADDR,
        m_axi_data_port_AWID,
        m_axi_data_port_AWLEN,
        m_axi_data_port_AWSIZE,
        m_axi_data_port_AWBURST,
        m_axi_data_port_AWLOCK,
        m_axi_data_port_AWCACHE,
        m_axi_data_port_AWPROT,
        m_axi_data_port_AWQOS,
        m_axi_data_port_AWREGION,
        m_axi_data_port_AWUSER,
        m_axi_data_port_WVALID,
        m_axi_data_port_WREADY,
        m_axi_data_port_WDATA,
        m_axi_data_port_WSTRB,
        m_axi_data_port_WLAST,
        m_axi_data_port_WID,
        m_axi_data_port_WUSER,
        m_axi_data_port_ARVALID,
        m_axi_data_port_ARREADY,
        m_axi_data_port_ARADDR,
        m_axi_data_port_ARID,
        m_axi_data_port_ARLEN,
        m_axi_data_port_ARSIZE,
        m_axi_data_port_ARBURST,
        m_axi_data_port_ARLOCK,
        m_axi_data_port_ARCACHE,
        m_axi_data_port_ARPROT,
        m_axi_data_port_ARQOS,
        m_axi_data_port_ARREGION,
        m_axi_data_port_ARUSER,
        m_axi_data_port_RVALID,
        m_axi_data_port_RREADY,
        m_axi_data_port_RDATA,
        m_axi_data_port_RLAST,
        m_axi_data_port_RID,
        m_axi_data_port_RUSER,
        m_axi_data_port_RRESP,
        m_axi_data_port_BVALID,
        m_axi_data_port_BREADY,
        m_axi_data_port_BRESP,
        m_axi_data_port_BID,
        m_axi_data_port_BUSER,
        load_queue_V_V_TDATA,
        load_queue_V_V_TVALID,
        load_queue_V_V_TREADY,
        g2l_dep_queue_V_TDATA,
        g2l_dep_queue_V_TVALID,
        g2l_dep_queue_V_TREADY,
        l2g_dep_queue_V_TDATA,
        l2g_dep_queue_V_TVALID,
        l2g_dep_queue_V_TREADY,
        inp_mem_V_Addr_A,
        inp_mem_V_EN_A,
        inp_mem_V_WEN_A,
        inp_mem_V_Din_A,
        inp_mem_V_Dout_A,
        inp_mem_V_Clk_A,
        inp_mem_V_Rst_A,
        wgt_mem_0_V_Addr_A,
        wgt_mem_0_V_EN_A,
        wgt_mem_0_V_WEN_A,
        wgt_mem_0_V_Din_A,
        wgt_mem_0_V_Dout_A,
        wgt_mem_0_V_Clk_A,
        wgt_mem_0_V_Rst_A,
        wgt_mem_1_V_Addr_A,
        wgt_mem_1_V_EN_A,
        wgt_mem_1_V_WEN_A,
        wgt_mem_1_V_Din_A,
        wgt_mem_1_V_Dout_A,
        wgt_mem_1_V_Clk_A,
        wgt_mem_1_V_Rst_A,
        s_axi_CONTROL_BUS_AWVALID,
        s_axi_CONTROL_BUS_AWREADY,
        s_axi_CONTROL_BUS_AWADDR,
        s_axi_CONTROL_BUS_WVALID,
        s_axi_CONTROL_BUS_WREADY,
        s_axi_CONTROL_BUS_WDATA,
        s_axi_CONTROL_BUS_WSTRB,
        s_axi_CONTROL_BUS_ARVALID,
        s_axi_CONTROL_BUS_ARREADY,
        s_axi_CONTROL_BUS_ARADDR,
        s_axi_CONTROL_BUS_RVALID,
        s_axi_CONTROL_BUS_RREADY,
        s_axi_CONTROL_BUS_RDATA,
        s_axi_CONTROL_BUS_RRESP,
        s_axi_CONTROL_BUS_BVALID,
        s_axi_CONTROL_BUS_BREADY,
        s_axi_CONTROL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_pp0_stage0 = 28'd1024;
parameter    ap_ST_fsm_pp0_stage1 = 28'd2048;
parameter    ap_ST_fsm_state15 = 28'd4096;
parameter    ap_ST_fsm_state16 = 28'd8192;
parameter    ap_ST_fsm_state17 = 28'd16384;
parameter    ap_ST_fsm_state18 = 28'd32768;
parameter    ap_ST_fsm_state19 = 28'd65536;
parameter    ap_ST_fsm_state20 = 28'd131072;
parameter    ap_ST_fsm_state21 = 28'd262144;
parameter    ap_ST_fsm_state22 = 28'd524288;
parameter    ap_ST_fsm_state23 = 28'd1048576;
parameter    ap_ST_fsm_state24 = 28'd2097152;
parameter    ap_ST_fsm_state25 = 28'd4194304;
parameter    ap_ST_fsm_pp1_stage0 = 28'd8388608;
parameter    ap_ST_fsm_state30 = 28'd16777216;
parameter    ap_ST_fsm_state31 = 28'd33554432;
parameter    ap_ST_fsm_state32 = 28'd67108864;
parameter    ap_ST_fsm_state33 = 28'd134217728;
parameter    C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA_PORT_ID_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_PORT_DATA_WIDTH = 64;
parameter    C_M_AXI_DATA_PORT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_WUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_RUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_PORT_USER_VALUE = 0;
parameter    C_M_AXI_DATA_PORT_PROT_VALUE = 0;
parameter    C_M_AXI_DATA_PORT_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_DATA_PORT_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_data_port_AWVALID;
input   m_axi_data_port_AWREADY;
output  [C_M_AXI_DATA_PORT_ADDR_WIDTH - 1:0] m_axi_data_port_AWADDR;
output  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_AWID;
output  [7:0] m_axi_data_port_AWLEN;
output  [2:0] m_axi_data_port_AWSIZE;
output  [1:0] m_axi_data_port_AWBURST;
output  [1:0] m_axi_data_port_AWLOCK;
output  [3:0] m_axi_data_port_AWCACHE;
output  [2:0] m_axi_data_port_AWPROT;
output  [3:0] m_axi_data_port_AWQOS;
output  [3:0] m_axi_data_port_AWREGION;
output  [C_M_AXI_DATA_PORT_AWUSER_WIDTH - 1:0] m_axi_data_port_AWUSER;
output   m_axi_data_port_WVALID;
input   m_axi_data_port_WREADY;
output  [C_M_AXI_DATA_PORT_DATA_WIDTH - 1:0] m_axi_data_port_WDATA;
output  [C_M_AXI_DATA_PORT_WSTRB_WIDTH - 1:0] m_axi_data_port_WSTRB;
output   m_axi_data_port_WLAST;
output  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_WID;
output  [C_M_AXI_DATA_PORT_WUSER_WIDTH - 1:0] m_axi_data_port_WUSER;
output   m_axi_data_port_ARVALID;
input   m_axi_data_port_ARREADY;
output  [C_M_AXI_DATA_PORT_ADDR_WIDTH - 1:0] m_axi_data_port_ARADDR;
output  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_ARID;
output  [7:0] m_axi_data_port_ARLEN;
output  [2:0] m_axi_data_port_ARSIZE;
output  [1:0] m_axi_data_port_ARBURST;
output  [1:0] m_axi_data_port_ARLOCK;
output  [3:0] m_axi_data_port_ARCACHE;
output  [2:0] m_axi_data_port_ARPROT;
output  [3:0] m_axi_data_port_ARQOS;
output  [3:0] m_axi_data_port_ARREGION;
output  [C_M_AXI_DATA_PORT_ARUSER_WIDTH - 1:0] m_axi_data_port_ARUSER;
input   m_axi_data_port_RVALID;
output   m_axi_data_port_RREADY;
input  [C_M_AXI_DATA_PORT_DATA_WIDTH - 1:0] m_axi_data_port_RDATA;
input   m_axi_data_port_RLAST;
input  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_RID;
input  [C_M_AXI_DATA_PORT_RUSER_WIDTH - 1:0] m_axi_data_port_RUSER;
input  [1:0] m_axi_data_port_RRESP;
input   m_axi_data_port_BVALID;
output   m_axi_data_port_BREADY;
input  [1:0] m_axi_data_port_BRESP;
input  [C_M_AXI_DATA_PORT_ID_WIDTH - 1:0] m_axi_data_port_BID;
input  [C_M_AXI_DATA_PORT_BUSER_WIDTH - 1:0] m_axi_data_port_BUSER;
input  [127:0] load_queue_V_V_TDATA;
input   load_queue_V_V_TVALID;
output   load_queue_V_V_TREADY;
input  [7:0] g2l_dep_queue_V_TDATA;
input   g2l_dep_queue_V_TVALID;
output   g2l_dep_queue_V_TREADY;
output  [7:0] l2g_dep_queue_V_TDATA;
output   l2g_dep_queue_V_TVALID;
input   l2g_dep_queue_V_TREADY;
output  [31:0] inp_mem_V_Addr_A;
output   inp_mem_V_EN_A;
output  [15:0] inp_mem_V_WEN_A;
output  [127:0] inp_mem_V_Din_A;
input  [127:0] inp_mem_V_Dout_A;
output   inp_mem_V_Clk_A;
output   inp_mem_V_Rst_A;
output  [31:0] wgt_mem_0_V_Addr_A;
output   wgt_mem_0_V_EN_A;
output  [127:0] wgt_mem_0_V_WEN_A;
output  [1023:0] wgt_mem_0_V_Din_A;
input  [1023:0] wgt_mem_0_V_Dout_A;
output   wgt_mem_0_V_Clk_A;
output   wgt_mem_0_V_Rst_A;
output  [31:0] wgt_mem_1_V_Addr_A;
output   wgt_mem_1_V_EN_A;
output  [127:0] wgt_mem_1_V_WEN_A;
output  [1023:0] wgt_mem_1_V_Din_A;
input  [1023:0] wgt_mem_1_V_Dout_A;
output   wgt_mem_1_V_Clk_A;
output   wgt_mem_1_V_Rst_A;
input   s_axi_CONTROL_BUS_AWVALID;
output   s_axi_CONTROL_BUS_AWREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR;
input   s_axi_CONTROL_BUS_WVALID;
output   s_axi_CONTROL_BUS_WREADY;
input  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA;
input  [C_S_AXI_CONTROL_BUS_WSTRB_WIDTH - 1:0] s_axi_CONTROL_BUS_WSTRB;
input   s_axi_CONTROL_BUS_ARVALID;
output   s_axi_CONTROL_BUS_ARREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR;
output   s_axi_CONTROL_BUS_RVALID;
input   s_axi_CONTROL_BUS_RREADY;
output  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA;
output  [1:0] s_axi_CONTROL_BUS_RRESP;
output   s_axi_CONTROL_BUS_BVALID;
input   s_axi_CONTROL_BUS_BREADY;
output  [1:0] s_axi_CONTROL_BUS_BRESP;
output   interrupt;

reg load_queue_V_V_TREADY;
reg g2l_dep_queue_V_TREADY;
reg[31:0] inp_mem_V_Addr_A;
reg inp_mem_V_EN_A;
reg[15:0] inp_mem_V_WEN_A;
reg[127:0] inp_mem_V_Din_A;
reg wgt_mem_0_V_EN_A;
reg[127:0] wgt_mem_0_V_WEN_A;
reg wgt_mem_1_V_EN_A;
reg[127:0] wgt_mem_1_V_WEN_A;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] inputs_V;
wire   [31:0] weights_V;
reg    data_port_blk_n_AR;
wire    ap_CS_fsm_state19;
reg    data_port_blk_n_R;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] icmp_ln67_reg_1415;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln89_reg_1277;
reg    load_queue_V_V_TDATA_blk_n;
reg    g2l_dep_queue_V_TDATA_blk_n;
wire   [0:0] tmp_2_fu_508_p3;
reg    l2g_dep_queue_V_TDATA_blk_n;
wire    ap_CS_fsm_state32;
wire   [0:0] tmp_7_fu_1155_p3;
wire    ap_CS_fsm_state33;
reg   [0:0] tmp_7_reg_1471;
wire    data_port_AWREADY;
wire    data_port_WREADY;
reg    data_port_ARVALID;
wire    data_port_ARREADY;
reg   [31:0] data_port_ARADDR;
reg   [31:0] data_port_ARLEN;
wire    data_port_RVALID;
reg    data_port_RREADY;
wire   [63:0] data_port_RDATA;
wire    data_port_RLAST;
wire   [0:0] data_port_RID;
wire   [0:0] data_port_RUSER;
wire   [1:0] data_port_RRESP;
wire    data_port_BVALID;
wire   [1:0] data_port_BRESP;
wire   [0:0] data_port_BID;
wire   [0:0] data_port_BUSER;
reg   [20:0] phi_ln89_reg_365;
reg   [16:0] phi_ln67_reg_407;
reg   [15:0] reg_464;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln206_fu_618_p2;
wire   [0:0] icmp_ln219_fu_624_p2;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    grp_reset_mem_ap_uint_64_2_s_fu_418_ap_ready;
wire    grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done;
reg   [15:0] reg_476;
wire   [37:0] p_cast8_fu_490_p1;
reg   [37:0] p_cast8_reg_1162;
reg    ap_block_state1;
wire   [33:0] p_cast7_fu_504_p1;
reg   [33:0] p_cast7_reg_1167;
reg   [127:0] tmp_V_reg_1172;
wire   [127:0] lshr_ln200_fu_516_p2;
wire   [3:0] trunc_ln200_fu_522_p1;
reg   [3:0] trunc_ln200_reg_1191;
wire   [15:0] trunc_ln200_1_fu_530_p4;
reg   [15:0] trunc_ln200_1_reg_1196;
wire   [3:0] trunc_ln200_2_fu_546_p1;
reg   [3:0] trunc_ln200_2_reg_1204;
wire  signed [15:0] x_width_V_fu_564_p2;
reg  signed [15:0] x_width_V_reg_1209;
wire   [15:0] zext_ln200_1_fu_570_p1;
reg   [15:0] zext_ln200_1_reg_1215;
wire   [15:0] y_offset_0_V_fu_586_p2;
reg   [15:0] y_offset_0_V_reg_1220;
wire   [15:0] y_offset_1_V_fu_604_p2;
reg   [15:0] y_offset_1_V_reg_1225;
reg   [0:0] icmp_ln206_reg_1230;
reg   [0:0] icmp_ln219_reg_1234;
wire   [31:0] zext_ln700_1_fu_630_p1;
reg   [31:0] zext_ln700_1_reg_1238;
wire   [20:0] shl_ln1_fu_634_p3;
reg   [20:0] shl_ln1_reg_1243;
wire   [31:0] zext_ln89_fu_641_p1;
reg   [31:0] zext_ln89_reg_1248;
wire   [15:0] y_1_fu_651_p2;
reg   [15:0] y_1_reg_1256;
wire    ap_CS_fsm_state3;
wire   [37:0] add_ln88_fu_669_p2;
reg   [37:0] add_ln88_reg_1261;
wire   [0:0] icmp_ln86_fu_645_p2;
wire   [16:0] shl_ln89_1_fu_688_p3;
reg   [16:0] shl_ln89_1_reg_1272;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln89_fu_696_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state11_pp0_stage0_iter0;
wire    ap_block_state13_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [20:0] add_ln89_fu_701_p2;
reg   [20:0] add_ln89_reg_1281;
wire   [0:0] trunc_ln89_2_fu_711_p1;
reg   [0:0] trunc_ln89_2_reg_1286;
reg   [0:0] trunc_ln89_2_reg_1286_pp0_iter1_reg;
reg   [11:0] lshr_ln1_reg_1291;
reg   [3:0] tmp_9_reg_1296;
reg   [63:0] data_port_addr_1_read_reg_1301;
reg    ap_block_state12_pp0_stage1_iter0;
wire    ap_block_state14_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
wire   [9:0] shl_ln89_2_fu_740_p3;
reg   [9:0] shl_ln89_2_reg_1306;
wire   [9:0] empty_20_fu_747_p2;
reg   [9:0] empty_20_reg_1311;
wire   [0:0] icmp_ln89_1_fu_753_p2;
reg   [0:0] icmp_ln89_1_reg_1316;
reg   [9:0] wgt_mem_0_V_addr_reg_1324;
reg   [9:0] wgt_mem_1_V_addr_reg_1329;
wire   [1023:0] shl_ln89_fu_818_p2;
reg   [1023:0] shl_ln89_reg_1334;
wire   [1023:0] and_ln89_fu_836_p2;
reg   [1023:0] and_ln89_reg_1340;
wire   [15:0] add_ln700_2_fu_888_p2;
wire    ap_CS_fsm_state15;
wire   [31:0] add_ln700_3_fu_893_p2;
wire   [15:0] grp_reset_mem_ap_uint_64_2_s_fu_418_ap_return;
wire   [15:0] zext_ln209_1_fu_898_p1;
reg   [15:0] zext_ln209_1_reg_1361;
wire   [31:0] zext_ln700_fu_901_p1;
reg   [31:0] zext_ln700_reg_1366;
wire   [16:0] shl_ln_fu_905_p3;
reg   [16:0] shl_ln_reg_1371;
wire   [31:0] zext_ln67_fu_912_p1;
reg   [31:0] zext_ln67_reg_1376;
wire   [15:0] y_fu_922_p2;
reg   [15:0] y_reg_1384;
wire    ap_CS_fsm_state18;
wire   [33:0] add_ln66_fu_940_p2;
reg   [33:0] add_ln66_reg_1389;
wire   [0:0] icmp_ln62_fu_916_p2;
reg   [15:0] sram_idx_V_assign_3_reg_1394;
wire   [12:0] trunc_ln67_fu_955_p1;
reg   [12:0] trunc_ln67_reg_1405;
wire   [13:0] shl_ln67_1_fu_959_p3;
reg   [13:0] shl_ln67_1_reg_1410;
wire    ap_CS_fsm_state25;
wire   [0:0] icmp_ln67_fu_966_p2;
wire    ap_block_state26_pp1_stage0_iter0;
reg    ap_block_state27_pp1_stage0_iter1;
wire    ap_block_state28_pp1_stage0_iter2;
wire    ap_block_state29_pp1_stage0_iter3;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] icmp_ln67_reg_1415_pp1_iter1_reg;
reg   [0:0] icmp_ln67_reg_1415_pp1_iter2_reg;
wire   [16:0] add_ln67_fu_971_p2;
reg    ap_enable_reg_pp1_iter0;
reg   [12:0] lshr_ln_reg_1424;
reg   [12:0] lshr_ln_reg_1424_pp1_iter1_reg;
reg   [12:0] lshr_ln_reg_1424_pp1_iter2_reg;
wire   [0:0] trunc_ln67_2_fu_996_p1;
reg   [0:0] trunc_ln67_2_reg_1429;
reg   [0:0] trunc_ln67_2_reg_1429_pp1_iter1_reg;
reg   [0:0] trunc_ln67_2_reg_1429_pp1_iter2_reg;
reg   [63:0] data_port_addr_read_reg_1435;
wire   [0:0] icmp_ln67_1_fu_1013_p2;
reg   [0:0] icmp_ln67_1_reg_1440;
wire   [127:0] shl_ln67_fu_1078_p2;
reg   [127:0] shl_ln67_reg_1445;
wire   [127:0] and_ln67_fu_1096_p2;
reg   [127:0] and_ln67_reg_1451;
wire   [15:0] add_ln700_fu_1145_p2;
reg   [15:0] add_ln700_reg_1456;
wire    ap_CS_fsm_state30;
wire   [31:0] add_ln700_1_fu_1150_p2;
reg   [31:0] add_ln700_1_reg_1461;
wire    ap_CS_fsm_state31;
reg    ap_block_state32_io;
reg    ap_block_state32_on_subcall_done;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state11;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state26;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
wire    grp_reset_mem_ap_uint_64_2_s_fu_418_ap_start;
wire    grp_reset_mem_ap_uint_64_2_s_fu_418_ap_idle;
reg   [15:0] grp_reset_mem_ap_uint_64_2_s_fu_418_sram_idx_V_read;
reg   [15:0] grp_reset_mem_ap_uint_64_2_s_fu_418_range_V;
wire   [31:0] grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_Addr_A;
wire    grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_EN_A;
wire   [15:0] grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_WEN_A;
wire   [127:0] grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_Din_A;
reg   [15:0] sram_idx_V_assign_1_0_reg_334;
reg   [31:0] dram_idx_assign_1_0_reg_344;
reg   [15:0] i_op_assign_1_reg_354;
reg   [20:0] ap_phi_mux_phi_ln89_phi_fu_369_p4;
wire    ap_block_pp0_stage0;
reg   [15:0] sram_idx_V_assign_0_reg_376;
reg   [31:0] dram_idx_assign_0_reg_386;
reg   [15:0] i_op_assign_reg_396;
reg    grp_reset_mem_ap_uint_64_2_s_fu_418_ap_start_reg;
wire   [63:0] zext_ln89_1_fu_759_p1;
wire   [63:0] zext_ln67_1_fu_1102_p1;
wire   [63:0] zext_ln88_fu_674_p1;
wire   [63:0] zext_ln66_fu_945_p1;
reg   [31:0] wgt_mem_1_V_Addr_A_orig;
wire   [1023:0] or_ln89_fu_880_p2;
reg   [31:0] wgt_mem_0_V_Addr_A_orig;
wire   [31:0] inp_mem_V_Addr_A_orig;
wire   [127:0] and_ln67_1_fu_1121_p2;
wire   [15:0] shl_ln67_4_fu_1138_p2;
wire   [28:0] tmp_fu_480_p4;
wire   [28:0] tmp_1_fu_494_p4;
wire   [127:0] lshr_ln200_1_fu_540_p2;
wire   [4:0] zext_ln301_fu_550_p1;
wire   [4:0] zext_ln200_fu_526_p1;
wire   [4:0] add_ln301_fu_554_p2;
wire   [15:0] zext_ln301_1_fu_560_p1;
wire   [3:0] trunc_ln1_fu_573_p4;
wire   [3:0] y_offset_0_V_fu_586_p1;
wire   [3:0] trunc_ln209_1_fu_591_p4;
wire   [3:0] y_offset_1_V_fu_604_p1;
wire   [1:0] trunc_ln2_fu_609_p4;
wire   [15:0] grp_fu_455_p4;
wire   [36:0] ret_V_1_fu_657_p3;
wire   [37:0] zext_ln1352_1_fu_665_p1;
wire   [11:0] trunc_ln89_fu_684_p1;
wire   [16:0] trunc_ln89_1_fu_707_p1;
wire   [16:0] add_ln89_1_fu_715_p2;
wire   [10:0] zext_ln89_2_fu_764_p1;
wire   [10:0] zext_ln89_3_fu_767_p1;
wire   [10:0] xor_ln89_fu_773_p2;
wire   [10:0] select_ln89_1_fu_779_p3;
wire   [10:0] select_ln89_3_fu_793_p3;
wire   [10:0] select_ln89_2_fu_786_p3;
wire   [10:0] xor_ln89_1_fu_800_p2;
wire   [1023:0] zext_ln89_4_fu_770_p1;
wire   [1023:0] zext_ln89_5_fu_806_p1;
wire   [1023:0] zext_ln89_6_fu_810_p1;
wire   [1023:0] zext_ln89_7_fu_814_p1;
wire   [1023:0] shl_ln89_3_fu_824_p2;
wire   [1023:0] lshr_ln89_fu_830_p2;
reg   [1023:0] tmp_8_fu_849_p4;
wire   [1023:0] select_ln89_fu_842_p3;
wire   [1023:0] xor_ln89_2_fu_864_p2;
wire   [1023:0] select_ln89_4_fu_858_p3;
wire   [1023:0] and_ln89_1_fu_869_p2;
wire   [1023:0] and_ln89_2_fu_875_p2;
wire   [32:0] ret_V_fu_928_p3;
wire   [33:0] zext_ln1352_fu_936_p1;
wire   [13:0] trunc_ln67_1_fu_977_p1;
wire   [13:0] add_ln67_1_fu_981_p2;
wire   [6:0] shl_ln67_2_fu_1000_p3;
wire   [6:0] empty_17_fu_1007_p2;
wire   [7:0] zext_ln67_2_fu_1019_p1;
wire   [7:0] zext_ln67_3_fu_1023_p1;
wire   [7:0] xor_ln67_fu_1030_p2;
wire   [7:0] select_ln67_fu_1036_p3;
wire   [7:0] select_ln67_2_fu_1052_p3;
wire   [7:0] select_ln67_1_fu_1044_p3;
wire   [7:0] xor_ln67_1_fu_1060_p2;
wire   [127:0] zext_ln67_4_fu_1027_p1;
wire   [127:0] zext_ln67_5_fu_1066_p1;
wire   [127:0] zext_ln67_6_fu_1070_p1;
wire   [127:0] zext_ln67_7_fu_1074_p1;
wire   [127:0] shl_ln67_3_fu_1084_p2;
wire   [127:0] lshr_ln67_fu_1090_p2;
reg   [127:0] tmp_3_fu_1106_p4;
wire   [127:0] select_ln67_3_fu_1115_p3;
wire   [3:0] tmp_5_fu_1127_p3;
wire   [15:0] zext_ln67_8_fu_1134_p1;
wire    regslice_both_l2g_dep_queue_V_U_apdone_blk;
reg    ap_block_state33_io;
reg   [27:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire    regslice_both_load_queue_V_V_U_apdone_blk;
wire   [127:0] load_queue_V_V_TDATA_int;
wire    load_queue_V_V_TVALID_int;
reg    load_queue_V_V_TREADY_int;
wire    regslice_both_load_queue_V_V_U_ack_in;
wire    regslice_both_g2l_dep_queue_V_U_apdone_blk;
wire   [7:0] g2l_dep_queue_V_TDATA_int;
wire    g2l_dep_queue_V_TVALID_int;
reg    g2l_dep_queue_V_TREADY_int;
wire    regslice_both_g2l_dep_queue_V_U_ack_in;
reg    l2g_dep_queue_V_TVALID_int;
wire    l2g_dep_queue_V_TREADY_int;
wire    regslice_both_l2g_dep_queue_V_U_vld_out;
wire   [15:0] y_offset_0_V_fu_586_p10;
wire   [15:0] y_offset_1_V_fu_604_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 grp_reset_mem_ap_uint_64_2_s_fu_418_ap_start_reg = 1'b0;
end

load_CONTROL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_BUS_DATA_WIDTH ))
load_CONTROL_BUS_s_axi_U(
    .AWVALID(s_axi_CONTROL_BUS_AWVALID),
    .AWREADY(s_axi_CONTROL_BUS_AWREADY),
    .AWADDR(s_axi_CONTROL_BUS_AWADDR),
    .WVALID(s_axi_CONTROL_BUS_WVALID),
    .WREADY(s_axi_CONTROL_BUS_WREADY),
    .WDATA(s_axi_CONTROL_BUS_WDATA),
    .WSTRB(s_axi_CONTROL_BUS_WSTRB),
    .ARVALID(s_axi_CONTROL_BUS_ARVALID),
    .ARREADY(s_axi_CONTROL_BUS_ARREADY),
    .ARADDR(s_axi_CONTROL_BUS_ARADDR),
    .RVALID(s_axi_CONTROL_BUS_RVALID),
    .RREADY(s_axi_CONTROL_BUS_RREADY),
    .RDATA(s_axi_CONTROL_BUS_RDATA),
    .RRESP(s_axi_CONTROL_BUS_RRESP),
    .BVALID(s_axi_CONTROL_BUS_BVALID),
    .BREADY(s_axi_CONTROL_BUS_BREADY),
    .BRESP(s_axi_CONTROL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .inputs_V(inputs_V),
    .weights_V(weights_V)
);

load_data_port_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 64 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DATA_PORT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DATA_PORT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DATA_PORT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DATA_PORT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DATA_PORT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DATA_PORT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DATA_PORT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DATA_PORT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_DATA_PORT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DATA_PORT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DATA_PORT_CACHE_VALUE ))
load_data_port_m_axi_U(
    .AWVALID(m_axi_data_port_AWVALID),
    .AWREADY(m_axi_data_port_AWREADY),
    .AWADDR(m_axi_data_port_AWADDR),
    .AWID(m_axi_data_port_AWID),
    .AWLEN(m_axi_data_port_AWLEN),
    .AWSIZE(m_axi_data_port_AWSIZE),
    .AWBURST(m_axi_data_port_AWBURST),
    .AWLOCK(m_axi_data_port_AWLOCK),
    .AWCACHE(m_axi_data_port_AWCACHE),
    .AWPROT(m_axi_data_port_AWPROT),
    .AWQOS(m_axi_data_port_AWQOS),
    .AWREGION(m_axi_data_port_AWREGION),
    .AWUSER(m_axi_data_port_AWUSER),
    .WVALID(m_axi_data_port_WVALID),
    .WREADY(m_axi_data_port_WREADY),
    .WDATA(m_axi_data_port_WDATA),
    .WSTRB(m_axi_data_port_WSTRB),
    .WLAST(m_axi_data_port_WLAST),
    .WID(m_axi_data_port_WID),
    .WUSER(m_axi_data_port_WUSER),
    .ARVALID(m_axi_data_port_ARVALID),
    .ARREADY(m_axi_data_port_ARREADY),
    .ARADDR(m_axi_data_port_ARADDR),
    .ARID(m_axi_data_port_ARID),
    .ARLEN(m_axi_data_port_ARLEN),
    .ARSIZE(m_axi_data_port_ARSIZE),
    .ARBURST(m_axi_data_port_ARBURST),
    .ARLOCK(m_axi_data_port_ARLOCK),
    .ARCACHE(m_axi_data_port_ARCACHE),
    .ARPROT(m_axi_data_port_ARPROT),
    .ARQOS(m_axi_data_port_ARQOS),
    .ARREGION(m_axi_data_port_ARREGION),
    .ARUSER(m_axi_data_port_ARUSER),
    .RVALID(m_axi_data_port_RVALID),
    .RREADY(m_axi_data_port_RREADY),
    .RDATA(m_axi_data_port_RDATA),
    .RLAST(m_axi_data_port_RLAST),
    .RID(m_axi_data_port_RID),
    .RUSER(m_axi_data_port_RUSER),
    .RRESP(m_axi_data_port_RRESP),
    .BVALID(m_axi_data_port_BVALID),
    .BREADY(m_axi_data_port_BREADY),
    .BRESP(m_axi_data_port_BRESP),
    .BID(m_axi_data_port_BID),
    .BUSER(m_axi_data_port_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(data_port_ARVALID),
    .I_ARREADY(data_port_ARREADY),
    .I_ARADDR(data_port_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(data_port_ARLEN),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(data_port_RVALID),
    .I_RREADY(data_port_RREADY),
    .I_RDATA(data_port_RDATA),
    .I_RID(data_port_RID),
    .I_RUSER(data_port_RUSER),
    .I_RRESP(data_port_RRESP),
    .I_RLAST(data_port_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(data_port_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(data_port_WREADY),
    .I_WDATA(64'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(8'd0),
    .I_BVALID(data_port_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(data_port_BRESP),
    .I_BID(data_port_BID),
    .I_BUSER(data_port_BUSER)
);

reset_mem_ap_uint_64_2_s grp_reset_mem_ap_uint_64_2_s_fu_418(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_reset_mem_ap_uint_64_2_s_fu_418_ap_start),
    .ap_done(grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done),
    .ap_idle(grp_reset_mem_ap_uint_64_2_s_fu_418_ap_idle),
    .ap_ready(grp_reset_mem_ap_uint_64_2_s_fu_418_ap_ready),
    .sram_idx_V_read(grp_reset_mem_ap_uint_64_2_s_fu_418_sram_idx_V_read),
    .range_V(grp_reset_mem_ap_uint_64_2_s_fu_418_range_V),
    .mem_V_Addr_A(grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_Addr_A),
    .mem_V_EN_A(grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_EN_A),
    .mem_V_WEN_A(grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_WEN_A),
    .mem_V_Din_A(grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_Din_A),
    .mem_V_Dout_A(128'd0),
    .ap_return(grp_reset_mem_ap_uint_64_2_s_fu_418_ap_return)
);

load_mul_16s_4ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
load_mul_16s_4ns_16_1_1_U3(
    .din0(x_width_V_reg_1209),
    .din1(y_offset_0_V_fu_586_p1),
    .dout(y_offset_0_V_fu_586_p2)
);

load_mul_16s_4ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
load_mul_16s_4ns_16_1_1_U4(
    .din0(x_width_V_reg_1209),
    .din1(y_offset_1_V_fu_604_p1),
    .dout(y_offset_1_V_fu_604_p2)
);

regslice_both #(
    .DataWidth( 128 ))
regslice_both_load_queue_V_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(load_queue_V_V_TDATA),
    .vld_in(load_queue_V_V_TVALID),
    .ack_in(regslice_both_load_queue_V_V_U_ack_in),
    .data_out(load_queue_V_V_TDATA_int),
    .vld_out(load_queue_V_V_TVALID_int),
    .ack_out(load_queue_V_V_TREADY_int),
    .apdone_blk(regslice_both_load_queue_V_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_g2l_dep_queue_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(g2l_dep_queue_V_TDATA),
    .vld_in(g2l_dep_queue_V_TVALID),
    .ack_in(regslice_both_g2l_dep_queue_V_U_ack_in),
    .data_out(g2l_dep_queue_V_TDATA_int),
    .vld_out(g2l_dep_queue_V_TVALID_int),
    .ack_out(g2l_dep_queue_V_TREADY_int),
    .apdone_blk(regslice_both_g2l_dep_queue_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_l2g_dep_queue_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd1),
    .vld_in(l2g_dep_queue_V_TVALID_int),
    .ack_in(l2g_dep_queue_V_TREADY_int),
    .data_out(l2g_dep_queue_V_TDATA),
    .vld_out(regslice_both_l2g_dep_queue_V_U_vld_out),
    .ack_out(l2g_dep_queue_V_TREADY),
    .apdone_blk(regslice_both_l2g_dep_queue_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state11) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state26) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state25)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state26)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state26);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end else if ((1'b1 == ap_CS_fsm_state25)) begin
            ap_enable_reg_pp1_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state18) & (icmp_ln62_fu_916_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state18) & (icmp_ln62_fu_916_p2 == 1'd0)))) begin
            grp_reset_mem_ap_uint_64_2_s_fu_418_ap_start_reg <= 1'b1;
        end else if ((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_ready == 1'b1)) begin
            grp_reset_mem_ap_uint_64_2_s_fu_418_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state31)) begin
            dram_idx_assign_0_reg_386 <= add_ln700_1_reg_1461;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            dram_idx_assign_0_reg_386 <= {{tmp_V_reg_1172[56:25]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dram_idx_assign_1_0_reg_344 <= add_ln700_3_fu_893_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln219_fu_624_p2 == 1'd1) & (icmp_ln206_fu_618_p2 == 1'd0))) begin
        dram_idx_assign_1_0_reg_344 <= {{tmp_V_reg_1172[56:25]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        i_op_assign_1_reg_354 <= y_1_reg_1256;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln219_fu_624_p2 == 1'd1) & (icmp_ln206_fu_618_p2 == 1'd0))) begin
        i_op_assign_1_reg_354 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state31)) begin
            i_op_assign_reg_396 <= y_reg_1384;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            i_op_assign_reg_396 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln67_fu_966_p2 == 1'd0))) begin
        phi_ln67_reg_407 <= add_ln67_fu_971_p2;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        phi_ln67_reg_407 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_1277 == 1'd0))) begin
        phi_ln89_reg_365 <= add_ln89_reg_1281;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        phi_ln89_reg_365 <= 21'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        sram_idx_V_assign_1_0_reg_334 <= add_ln700_2_fu_888_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln219_fu_624_p2 == 1'd1) & (icmp_ln206_fu_618_p2 == 1'd0))) begin
        sram_idx_V_assign_1_0_reg_334 <= {{tmp_V_reg_1172[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (icmp_ln62_fu_916_p2 == 1'd0))) begin
        add_ln66_reg_1389 <= add_ln66_fu_940_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        add_ln700_1_reg_1461 <= add_ln700_1_fu_1150_p2;
        add_ln700_reg_1456 <= add_ln700_fu_1145_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln219_reg_1234 == 1'd1) & (icmp_ln86_fu_645_p2 == 1'd0))) begin
        add_ln88_reg_1261 <= add_ln88_fu_669_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        add_ln89_reg_1281 <= add_ln89_fu_701_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln67_reg_1415_pp1_iter1_reg == 1'd0))) begin
        and_ln67_reg_1451 <= and_ln67_fu_1096_p2;
        icmp_ln67_1_reg_1440 <= icmp_ln67_1_fu_1013_p2;
        shl_ln67_reg_1445 <= shl_ln67_fu_1078_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln89_reg_1340 <= and_ln89_fu_836_p2;
        icmp_ln89_reg_1277 <= icmp_ln89_fu_696_p2;
        shl_ln89_reg_1334 <= shl_ln89_fu_818_p2;
        trunc_ln89_2_reg_1286_pp0_iter1_reg <= trunc_ln89_2_reg_1286;
        wgt_mem_0_V_addr_reg_1324 <= zext_ln89_1_fu_759_p1;
        wgt_mem_1_V_addr_reg_1329 <= zext_ln89_1_fu_759_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln89_reg_1277 == 1'd0))) begin
        data_port_addr_1_read_reg_1301 <= data_port_RDATA;
        empty_20_reg_1311[9 : 6] <= empty_20_fu_747_p2[9 : 6];
        icmp_ln89_1_reg_1316 <= icmp_ln89_1_fu_753_p2;
        shl_ln89_2_reg_1306[9 : 6] <= shl_ln89_2_fu_740_p3[9 : 6];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln67_reg_1415 == 1'd0))) begin
        data_port_addr_read_reg_1435 <= data_port_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln206_reg_1230 <= icmp_ln206_fu_618_p2;
        y_offset_0_V_reg_1220 <= y_offset_0_V_fu_586_p2;
        y_offset_1_V_reg_1225 <= y_offset_1_V_fu_604_p2;
        zext_ln200_1_reg_1215[3 : 0] <= zext_ln200_1_fu_570_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln206_fu_618_p2 == 1'd0))) begin
        icmp_ln219_reg_1234 <= icmp_ln219_fu_624_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln67_reg_1415 <= icmp_ln67_fu_966_p2;
        icmp_ln67_reg_1415_pp1_iter1_reg <= icmp_ln67_reg_1415;
        lshr_ln_reg_1424_pp1_iter1_reg <= lshr_ln_reg_1424;
        trunc_ln67_2_reg_1429_pp1_iter1_reg <= trunc_ln67_2_reg_1429;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        icmp_ln67_reg_1415_pp1_iter2_reg <= icmp_ln67_reg_1415_pp1_iter1_reg;
        lshr_ln_reg_1424_pp1_iter2_reg <= lshr_ln_reg_1424_pp1_iter1_reg;
        trunc_ln67_2_reg_1429_pp1_iter2_reg <= trunc_ln67_2_reg_1429_pp1_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_696_p2 == 1'd0))) begin
        lshr_ln1_reg_1291 <= {{add_ln89_1_fu_715_p2[16:5]}};
        tmp_9_reg_1296 <= {{ap_phi_mux_phi_ln89_phi_fu_369_p4[4:1]}};
        trunc_ln89_2_reg_1286 <= trunc_ln89_2_fu_711_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln67_fu_966_p2 == 1'd0))) begin
        lshr_ln_reg_1424 <= {{add_ln67_1_fu_981_p2[13:1]}};
        trunc_ln67_2_reg_1429 <= trunc_ln67_2_fu_996_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (load_queue_V_V_TVALID_int == 1'b0) | ((g2l_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_508_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1))) begin
        p_cast7_reg_1167[28 : 0] <= p_cast7_fu_504_p1[28 : 0];
        p_cast8_reg_1162[28 : 0] <= p_cast8_fu_490_p1[28 : 0];
        tmp_V_reg_1172 <= load_queue_V_V_TDATA_int;
        trunc_ln200_1_reg_1196 <= {{load_queue_V_V_TDATA_int[95:80]}};
        trunc_ln200_2_reg_1204 <= trunc_ln200_2_fu_546_p1;
        trunc_ln200_reg_1191 <= trunc_ln200_fu_522_p1;
        x_width_V_reg_1209 <= x_width_V_fu_564_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln219_fu_624_p2 == 1'd1) & (icmp_ln206_fu_618_p2 == 1'd0)))) begin
        reg_464 <= {{tmp_V_reg_1172[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln219_fu_624_p2 == 1'd1) & (icmp_ln206_fu_618_p2 == 1'd0)))) begin
        reg_476 <= {{tmp_V_reg_1172[79:64]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln219_fu_624_p2 == 1'd1) & (icmp_ln206_fu_618_p2 == 1'd0))) begin
        shl_ln1_reg_1243[20 : 5] <= shl_ln1_fu_634_p3[20 : 5];
        zext_ln700_1_reg_1238[15 : 0] <= zext_ln700_1_fu_630_p1[15 : 0];
        zext_ln89_reg_1248[20 : 5] <= zext_ln89_fu_641_p1[20 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        shl_ln67_1_reg_1410[13 : 1] <= shl_ln67_1_fu_959_p3[13 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        shl_ln89_1_reg_1272[16 : 5] <= shl_ln89_1_fu_688_p3[16 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        shl_ln_reg_1371[16 : 1] <= shl_ln_fu_905_p3[16 : 1];
        zext_ln209_1_reg_1361[3 : 0] <= zext_ln209_1_fu_898_p1[3 : 0];
        zext_ln67_reg_1376[16 : 1] <= zext_ln67_fu_912_p1[16 : 1];
        zext_ln700_reg_1366[15 : 0] <= zext_ln700_fu_901_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31)) | ((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17)))) begin
        sram_idx_V_assign_0_reg_376 <= grp_reset_mem_ap_uint_64_2_s_fu_418_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b0) | (data_port_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
        sram_idx_V_assign_3_reg_1394 <= grp_reset_mem_ap_uint_64_2_s_fu_418_ap_return;
        trunc_ln67_reg_1405 <= trunc_ln67_fu_955_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state32_on_subcall_done) | (1'b1 == ap_block_state32_io)) & (1'b1 == ap_CS_fsm_state32))) begin
        tmp_7_reg_1471 <= tmp_V_reg_1172[32'd6];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln219_reg_1234 == 1'd1))) begin
        y_1_reg_1256 <= y_1_fu_651_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        y_reg_1384 <= y_fu_922_p2;
    end
end

always @ (*) begin
    if ((icmp_ln89_fu_696_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state11 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state11 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln67_fu_966_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state26 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state26 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state33_io) | (regslice_both_l2g_dep_queue_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state33))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_reg_1277 == 1'd0))) begin
        ap_phi_mux_phi_ln89_phi_fu_369_p4 = add_ln89_reg_1281;
    end else begin
        ap_phi_mux_phi_ln89_phi_fu_369_p4 = phi_ln89_reg_365;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state33_io) | (regslice_both_l2g_dep_queue_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state33))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b0) | (data_port_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
        data_port_ARADDR = zext_ln66_fu_945_p1;
    end else if (((data_port_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        data_port_ARADDR = zext_ln88_fu_674_p1;
    end else begin
        data_port_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b0) | (data_port_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
        data_port_ARLEN = zext_ln67_reg_1376;
    end else if (((data_port_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        data_port_ARLEN = zext_ln89_reg_1248;
    end else begin
        data_port_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((data_port_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | (~((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b0) | (data_port_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19)))) begin
        data_port_ARVALID = 1'b1;
    end else begin
        data_port_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln89_reg_1277 == 1'd0)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln67_reg_1415 == 1'd0)))) begin
        data_port_RREADY = 1'b1;
    end else begin
        data_port_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state19))) begin
        data_port_blk_n_AR = m_axi_data_port_ARREADY;
    end else begin
        data_port_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (icmp_ln89_reg_1277 == 1'd0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln67_reg_1415 == 1'd0) & (1'b0 == ap_block_pp1_stage0)))) begin
        data_port_blk_n_R = m_axi_data_port_RVALID;
    end else begin
        data_port_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_2_fu_508_p3 == 1'd1))) begin
        g2l_dep_queue_V_TDATA_blk_n = g2l_dep_queue_V_TVALID_int;
    end else begin
        g2l_dep_queue_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_both_g2l_dep_queue_V_U_ack_in == 1'b1) & (g2l_dep_queue_V_TVALID == 1'b1))) begin
        g2l_dep_queue_V_TREADY = 1'b1;
    end else begin
        g2l_dep_queue_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (load_queue_V_V_TVALID_int == 1'b0) | ((g2l_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_508_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1) & (tmp_2_fu_508_p3 == 1'd1))) begin
        g2l_dep_queue_V_TREADY_int = 1'b1;
    end else begin
        g2l_dep_queue_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_range_V = zext_ln200_1_reg_1215;
    end else if (((1'b1 == ap_CS_fsm_state32) & (icmp_ln206_reg_1230 == 1'd1))) begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_range_V = y_offset_1_V_reg_1225;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_range_V = zext_ln209_1_reg_1361;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_range_V = y_offset_0_V_reg_1220;
    end else begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_range_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_sram_idx_V_read = add_ln700_reg_1456;
    end else if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state32) & (icmp_ln206_reg_1230 == 1'd1)))) begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_sram_idx_V_read = sram_idx_V_assign_0_reg_376;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_sram_idx_V_read = reg_464;
    end else begin
        grp_reset_mem_ap_uint_64_2_s_fu_418_sram_idx_V_read = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state32) & (icmp_ln206_reg_1230 == 1'd1)))) begin
        inp_mem_V_Addr_A = grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_Addr_A;
    end else begin
        inp_mem_V_Addr_A = inp_mem_V_Addr_A_orig << 32'd4;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        inp_mem_V_Din_A = and_ln67_1_fu_1121_p2;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state32) & (icmp_ln206_reg_1230 == 1'd1)))) begin
        inp_mem_V_Din_A = grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_Din_A;
    end else begin
        inp_mem_V_Din_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        inp_mem_V_EN_A = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state32) & (icmp_ln206_reg_1230 == 1'd1)))) begin
        inp_mem_V_EN_A = grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_EN_A;
    end else begin
        inp_mem_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter3 == 1'b1) & (icmp_ln67_reg_1415_pp1_iter2_reg == 1'd0))) begin
        inp_mem_V_WEN_A = shl_ln67_4_fu_1138_p2;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state32) & (icmp_ln206_reg_1230 == 1'd1)))) begin
        inp_mem_V_WEN_A = grp_reset_mem_ap_uint_64_2_s_fu_418_mem_V_WEN_A;
    end else begin
        inp_mem_V_WEN_A = 16'd0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state33) & (tmp_7_reg_1471 == 1'd1)) | ((1'b1 == ap_CS_fsm_state32) & (tmp_7_fu_1155_p3 == 1'd1)))) begin
        l2g_dep_queue_V_TDATA_blk_n = l2g_dep_queue_V_TREADY_int;
    end else begin
        l2g_dep_queue_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state32_on_subcall_done) | (1'b1 == ap_block_state32_io)) & (1'b1 == ap_CS_fsm_state32) & (tmp_7_fu_1155_p3 == 1'd1))) begin
        l2g_dep_queue_V_TVALID_int = 1'b1;
    end else begin
        l2g_dep_queue_V_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        load_queue_V_V_TDATA_blk_n = load_queue_V_V_TVALID_int;
    end else begin
        load_queue_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_both_load_queue_V_V_U_ack_in == 1'b1) & (load_queue_V_V_TVALID == 1'b1))) begin
        load_queue_V_V_TREADY = 1'b1;
    end else begin
        load_queue_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (load_queue_V_V_TVALID_int == 1'b0) | ((g2l_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_508_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1))) begin
        load_queue_V_V_TREADY_int = 1'b1;
    end else begin
        load_queue_V_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            wgt_mem_0_V_Addr_A_orig = wgt_mem_0_V_addr_reg_1324;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            wgt_mem_0_V_Addr_A_orig = zext_ln89_1_fu_759_p1;
        end else begin
            wgt_mem_0_V_Addr_A_orig = 'bx;
        end
    end else begin
        wgt_mem_0_V_Addr_A_orig = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        wgt_mem_0_V_EN_A = 1'b1;
    end else begin
        wgt_mem_0_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln89_2_reg_1286_pp0_iter1_reg == 1'd0))) begin
        wgt_mem_0_V_WEN_A = 128'd340282366920938463463374607431768211455;
    end else begin
        wgt_mem_0_V_WEN_A = 128'd0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            wgt_mem_1_V_Addr_A_orig = wgt_mem_1_V_addr_reg_1329;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            wgt_mem_1_V_Addr_A_orig = zext_ln89_1_fu_759_p1;
        end else begin
            wgt_mem_1_V_Addr_A_orig = 'bx;
        end
    end else begin
        wgt_mem_1_V_Addr_A_orig = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        wgt_mem_1_V_EN_A = 1'b1;
    end else begin
        wgt_mem_1_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln89_2_reg_1286_pp0_iter1_reg == 1'd1))) begin
        wgt_mem_1_V_WEN_A = 128'd340282366920938463463374607431768211455;
    end else begin
        wgt_mem_1_V_WEN_A = 128'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (load_queue_V_V_TVALID_int == 1'b0) | ((g2l_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_508_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln206_fu_618_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln86_fu_645_p2 == 1'd1) | (icmp_ln219_reg_1234 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((data_port_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_696_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_696_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b0)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & (icmp_ln62_fu_916_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            if ((~((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b0) | (data_port_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln67_fu_966_p2 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b0)) & ~((ap_enable_reg_pp1_iter2 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter2 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter3 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln67_fu_966_p2 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            if ((~((1'b1 == ap_block_state32_on_subcall_done) | (1'b1 == ap_block_state32_io)) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            if ((~((1'b1 == ap_block_state33_io) | (regslice_both_l2g_dep_queue_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state33))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln301_fu_554_p2 = (zext_ln301_fu_550_p1 + zext_ln200_fu_526_p1);

assign add_ln66_fu_940_p2 = (p_cast7_reg_1167 + zext_ln1352_fu_936_p1);

assign add_ln67_1_fu_981_p2 = (shl_ln67_1_reg_1410 + trunc_ln67_1_fu_977_p1);

assign add_ln67_fu_971_p2 = (phi_ln67_reg_407 + 17'd1);

assign add_ln700_1_fu_1150_p2 = (zext_ln700_reg_1366 + dram_idx_assign_0_reg_386);

assign add_ln700_2_fu_888_p2 = (trunc_ln200_1_reg_1196 + sram_idx_V_assign_1_0_reg_334);

assign add_ln700_3_fu_893_p2 = (zext_ln700_1_reg_1238 + dram_idx_assign_1_0_reg_344);

assign add_ln700_fu_1145_p2 = (sram_idx_V_assign_3_reg_1394 + trunc_ln200_1_reg_1196);

assign add_ln88_fu_669_p2 = (p_cast8_reg_1162 + zext_ln1352_1_fu_665_p1);

assign add_ln89_1_fu_715_p2 = (trunc_ln89_1_fu_707_p1 + shl_ln89_1_reg_1272);

assign add_ln89_fu_701_p2 = (ap_phi_mux_phi_ln89_phi_fu_369_p4 + 21'd1);

assign and_ln67_1_fu_1121_p2 = (select_ln67_3_fu_1115_p3 & and_ln67_reg_1451);

assign and_ln67_fu_1096_p2 = (shl_ln67_3_fu_1084_p2 & lshr_ln67_fu_1090_p2);

assign and_ln89_1_fu_869_p2 = (xor_ln89_2_fu_864_p2 & select_ln89_fu_842_p3);

assign and_ln89_2_fu_875_p2 = (select_ln89_4_fu_858_p3 & and_ln89_reg_1340);

assign and_ln89_fu_836_p2 = (shl_ln89_3_fu_824_p2 & lshr_ln89_fu_830_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((data_port_RVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_reg_1277 == 1'd0));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((data_port_RVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_reg_1277 == 1'd0));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((data_port_RVALID == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln67_reg_1415 == 1'd0));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((data_port_RVALID == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln67_reg_1415 == 1'd0));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (load_queue_V_V_TVALID_int == 1'b0) | ((g2l_dep_queue_V_TVALID_int == 1'b0) & (tmp_2_fu_508_p3 == 1'd1)));
end

assign ap_block_state11_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage1_iter0 = ((data_port_RVALID == 1'b0) & (icmp_ln89_reg_1277 == 1'd0));
end

assign ap_block_state13_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state27_pp1_stage0_iter1 = ((data_port_RVALID == 1'b0) & (icmp_ln67_reg_1415 == 1'd0));
end

assign ap_block_state28_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state32_io = ((l2g_dep_queue_V_TREADY_int == 1'b0) & (tmp_7_fu_1155_p3 == 1'd1));
end

always @ (*) begin
    ap_block_state32_on_subcall_done = ((grp_reset_mem_ap_uint_64_2_s_fu_418_ap_done == 1'b0) & (icmp_ln206_reg_1230 == 1'd1));
end

always @ (*) begin
    ap_block_state33_io = ((l2g_dep_queue_V_TREADY_int == 1'b0) & (tmp_7_reg_1471 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_17_fu_1007_p2 = (shl_ln67_2_fu_1000_p3 | 7'd63);

assign empty_20_fu_747_p2 = (shl_ln89_2_fu_740_p3 | 10'd63);

assign grp_fu_455_p4 = {{tmp_V_reg_1172[111:96]}};

assign grp_reset_mem_ap_uint_64_2_s_fu_418_ap_start = grp_reset_mem_ap_uint_64_2_s_fu_418_ap_start_reg;

assign icmp_ln206_fu_618_p2 = ((trunc_ln2_fu_609_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln219_fu_624_p2 = ((trunc_ln2_fu_609_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_916_p2 = ((i_op_assign_reg_396 == reg_476) ? 1'b1 : 1'b0);

assign icmp_ln67_1_fu_1013_p2 = ((shl_ln67_2_fu_1000_p3 > empty_17_fu_1007_p2) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_966_p2 = ((phi_ln67_reg_407 == shl_ln_reg_1371) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_645_p2 = ((i_op_assign_1_reg_354 == reg_476) ? 1'b1 : 1'b0);

assign icmp_ln89_1_fu_753_p2 = ((shl_ln89_2_fu_740_p3 > empty_20_fu_747_p2) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_696_p2 = ((ap_phi_mux_phi_ln89_phi_fu_369_p4 == shl_ln1_reg_1243) ? 1'b1 : 1'b0);

assign inp_mem_V_Addr_A_orig = zext_ln67_1_fu_1102_p1;

assign inp_mem_V_Clk_A = ap_clk;

assign inp_mem_V_Rst_A = ap_rst_n_inv;

assign l2g_dep_queue_V_TVALID = regslice_both_l2g_dep_queue_V_U_vld_out;

assign lshr_ln200_1_fu_540_p2 = load_queue_V_V_TDATA_int >> 128'd124;

assign lshr_ln200_fu_516_p2 = load_queue_V_V_TDATA_int >> 128'd120;

assign lshr_ln67_fu_1090_p2 = 128'd340282366920938463463374607431768211455 >> zext_ln67_7_fu_1074_p1;

assign lshr_ln89_fu_830_p2 = 1024'd179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137215 >> zext_ln89_7_fu_814_p1;

assign or_ln89_fu_880_p2 = (and_ln89_2_fu_875_p2 | and_ln89_1_fu_869_p2);

assign p_cast7_fu_504_p1 = tmp_1_fu_494_p4;

assign p_cast8_fu_490_p1 = tmp_fu_480_p4;

assign ret_V_1_fu_657_p3 = {{dram_idx_assign_1_0_reg_344}, {5'd0}};

assign ret_V_fu_928_p3 = {{dram_idx_assign_0_reg_386}, {1'd0}};

assign select_ln67_1_fu_1044_p3 = ((icmp_ln67_1_fu_1013_p2[0:0] === 1'b1) ? zext_ln67_3_fu_1023_p1 : zext_ln67_2_fu_1019_p1);

assign select_ln67_2_fu_1052_p3 = ((icmp_ln67_1_fu_1013_p2[0:0] === 1'b1) ? xor_ln67_fu_1030_p2 : zext_ln67_2_fu_1019_p1);

assign select_ln67_3_fu_1115_p3 = ((icmp_ln67_1_reg_1440[0:0] === 1'b1) ? tmp_3_fu_1106_p4 : shl_ln67_reg_1445);

assign select_ln67_fu_1036_p3 = ((icmp_ln67_1_fu_1013_p2[0:0] === 1'b1) ? zext_ln67_2_fu_1019_p1 : zext_ln67_3_fu_1023_p1);

assign select_ln89_1_fu_779_p3 = ((icmp_ln89_1_reg_1316[0:0] === 1'b1) ? zext_ln89_2_fu_764_p1 : zext_ln89_3_fu_767_p1);

assign select_ln89_2_fu_786_p3 = ((icmp_ln89_1_reg_1316[0:0] === 1'b1) ? zext_ln89_3_fu_767_p1 : zext_ln89_2_fu_764_p1);

assign select_ln89_3_fu_793_p3 = ((icmp_ln89_1_reg_1316[0:0] === 1'b1) ? xor_ln89_fu_773_p2 : zext_ln89_2_fu_764_p1);

assign select_ln89_4_fu_858_p3 = ((icmp_ln89_1_reg_1316[0:0] === 1'b1) ? tmp_8_fu_849_p4 : shl_ln89_reg_1334);

assign select_ln89_fu_842_p3 = ((trunc_ln89_2_reg_1286_pp0_iter1_reg[0:0] === 1'b1) ? wgt_mem_1_V_Dout_A : wgt_mem_0_V_Dout_A);

assign shl_ln1_fu_634_p3 = {{trunc_ln200_1_reg_1196}, {5'd0}};

assign shl_ln67_1_fu_959_p3 = {{trunc_ln67_reg_1405}, {1'd0}};

assign shl_ln67_2_fu_1000_p3 = {{trunc_ln67_2_reg_1429_pp1_iter1_reg}, {6'd0}};

assign shl_ln67_3_fu_1084_p2 = 128'd340282366920938463463374607431768211455 << zext_ln67_6_fu_1070_p1;

assign shl_ln67_4_fu_1138_p2 = 16'd255 << zext_ln67_8_fu_1134_p1;

assign shl_ln67_fu_1078_p2 = zext_ln67_4_fu_1027_p1 << zext_ln67_5_fu_1066_p1;

assign shl_ln89_1_fu_688_p3 = {{trunc_ln89_fu_684_p1}, {5'd0}};

assign shl_ln89_2_fu_740_p3 = {{tmp_9_reg_1296}, {6'd0}};

assign shl_ln89_3_fu_824_p2 = 1024'd179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137215 << zext_ln89_6_fu_810_p1;

assign shl_ln89_fu_818_p2 = zext_ln89_4_fu_770_p1 << zext_ln89_5_fu_806_p1;

assign shl_ln_fu_905_p3 = {{trunc_ln200_1_reg_1196}, {1'd0}};

assign tmp_1_fu_494_p4 = {{inputs_V[31:3]}};

assign tmp_2_fu_508_p3 = load_queue_V_V_TDATA_int[32'd4];

integer ap_tvar_int_0;

always @ (shl_ln67_reg_1445) begin
    for (ap_tvar_int_0 = 128 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 127 - 0) begin
            tmp_3_fu_1106_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_3_fu_1106_p4[ap_tvar_int_0] = shl_ln67_reg_1445[127 - ap_tvar_int_0];
        end
    end
end

assign tmp_5_fu_1127_p3 = {{trunc_ln67_2_reg_1429_pp1_iter2_reg}, {3'd0}};

assign tmp_7_fu_1155_p3 = tmp_V_reg_1172[32'd6];

integer ap_tvar_int_1;

always @ (shl_ln89_reg_1334) begin
    for (ap_tvar_int_1 = 1024 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 1023 - 0) begin
            tmp_8_fu_849_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_8_fu_849_p4[ap_tvar_int_1] = shl_ln89_reg_1334[1023 - ap_tvar_int_1];
        end
    end
end

assign tmp_fu_480_p4 = {{weights_V[31:3]}};

assign trunc_ln1_fu_573_p4 = {{tmp_V_reg_1172[115:112]}};

assign trunc_ln200_1_fu_530_p4 = {{load_queue_V_V_TDATA_int[95:80]}};

assign trunc_ln200_2_fu_546_p1 = lshr_ln200_1_fu_540_p2[3:0];

assign trunc_ln200_fu_522_p1 = lshr_ln200_fu_516_p2[3:0];

assign trunc_ln209_1_fu_591_p4 = {{tmp_V_reg_1172[119:116]}};

assign trunc_ln2_fu_609_p4 = {{tmp_V_reg_1172[8:7]}};

assign trunc_ln67_1_fu_977_p1 = phi_ln67_reg_407[13:0];

assign trunc_ln67_2_fu_996_p1 = phi_ln67_reg_407[0:0];

assign trunc_ln67_fu_955_p1 = grp_reset_mem_ap_uint_64_2_s_fu_418_ap_return[12:0];

assign trunc_ln89_1_fu_707_p1 = ap_phi_mux_phi_ln89_phi_fu_369_p4[16:0];

assign trunc_ln89_2_fu_711_p1 = ap_phi_mux_phi_ln89_phi_fu_369_p4[0:0];

assign trunc_ln89_fu_684_p1 = sram_idx_V_assign_1_0_reg_334[11:0];

assign wgt_mem_0_V_Addr_A = wgt_mem_0_V_Addr_A_orig << 32'd7;

assign wgt_mem_0_V_Clk_A = ap_clk;

assign wgt_mem_0_V_Din_A = or_ln89_fu_880_p2;

assign wgt_mem_0_V_Rst_A = ap_rst_n_inv;

assign wgt_mem_1_V_Addr_A = wgt_mem_1_V_Addr_A_orig << 32'd7;

assign wgt_mem_1_V_Clk_A = ap_clk;

assign wgt_mem_1_V_Din_A = or_ln89_fu_880_p2;

assign wgt_mem_1_V_Rst_A = ap_rst_n_inv;

assign x_width_V_fu_564_p2 = (trunc_ln200_1_fu_530_p4 + zext_ln301_1_fu_560_p1);

assign xor_ln67_1_fu_1060_p2 = (select_ln67_fu_1036_p3 ^ 8'd127);

assign xor_ln67_fu_1030_p2 = (zext_ln67_2_fu_1019_p1 ^ 8'd127);

assign xor_ln89_1_fu_800_p2 = (select_ln89_1_fu_779_p3 ^ 11'd1023);

assign xor_ln89_2_fu_864_p2 = (1024'd179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137215 ^ and_ln89_reg_1340);

assign xor_ln89_fu_773_p2 = (zext_ln89_2_fu_764_p1 ^ 11'd1023);

assign y_1_fu_651_p2 = (i_op_assign_1_reg_354 + 16'd1);

assign y_fu_922_p2 = (i_op_assign_reg_396 + 16'd1);

assign y_offset_0_V_fu_586_p1 = y_offset_0_V_fu_586_p10;

assign y_offset_0_V_fu_586_p10 = trunc_ln1_fu_573_p4;

assign y_offset_1_V_fu_604_p1 = y_offset_1_V_fu_604_p10;

assign y_offset_1_V_fu_604_p10 = trunc_ln209_1_fu_591_p4;

assign zext_ln1352_1_fu_665_p1 = ret_V_1_fu_657_p3;

assign zext_ln1352_fu_936_p1 = ret_V_fu_928_p3;

assign zext_ln200_1_fu_570_p1 = trunc_ln200_2_reg_1204;

assign zext_ln200_fu_526_p1 = trunc_ln200_fu_522_p1;

assign zext_ln209_1_fu_898_p1 = trunc_ln200_reg_1191;

assign zext_ln301_1_fu_560_p1 = add_ln301_fu_554_p2;

assign zext_ln301_fu_550_p1 = trunc_ln200_2_fu_546_p1;

assign zext_ln66_fu_945_p1 = add_ln66_reg_1389;

assign zext_ln67_1_fu_1102_p1 = lshr_ln_reg_1424_pp1_iter2_reg;

assign zext_ln67_2_fu_1019_p1 = shl_ln67_2_fu_1000_p3;

assign zext_ln67_3_fu_1023_p1 = empty_17_fu_1007_p2;

assign zext_ln67_4_fu_1027_p1 = data_port_addr_read_reg_1435;

assign zext_ln67_5_fu_1066_p1 = select_ln67_2_fu_1052_p3;

assign zext_ln67_6_fu_1070_p1 = select_ln67_1_fu_1044_p3;

assign zext_ln67_7_fu_1074_p1 = xor_ln67_1_fu_1060_p2;

assign zext_ln67_8_fu_1134_p1 = tmp_5_fu_1127_p3;

assign zext_ln67_fu_912_p1 = shl_ln_fu_905_p3;

assign zext_ln700_1_fu_630_p1 = grp_fu_455_p4;

assign zext_ln700_fu_901_p1 = grp_fu_455_p4;

assign zext_ln88_fu_674_p1 = add_ln88_reg_1261;

assign zext_ln89_1_fu_759_p1 = lshr_ln1_reg_1291;

assign zext_ln89_2_fu_764_p1 = shl_ln89_2_reg_1306;

assign zext_ln89_3_fu_767_p1 = empty_20_reg_1311;

assign zext_ln89_4_fu_770_p1 = data_port_addr_1_read_reg_1301;

assign zext_ln89_5_fu_806_p1 = select_ln89_3_fu_793_p3;

assign zext_ln89_6_fu_810_p1 = select_ln89_2_fu_786_p3;

assign zext_ln89_7_fu_814_p1 = xor_ln89_1_fu_800_p2;

assign zext_ln89_fu_641_p1 = shl_ln1_fu_634_p3;

always @ (posedge ap_clk) begin
    p_cast8_reg_1162[37:29] <= 9'b000000000;
    p_cast7_reg_1167[33:29] <= 5'b00000;
    zext_ln200_1_reg_1215[15:4] <= 12'b000000000000;
    zext_ln700_1_reg_1238[31:16] <= 16'b0000000000000000;
    shl_ln1_reg_1243[4:0] <= 5'b00000;
    zext_ln89_reg_1248[4:0] <= 5'b00000;
    zext_ln89_reg_1248[31:21] <= 11'b00000000000;
    shl_ln89_1_reg_1272[4:0] <= 5'b00000;
    shl_ln89_2_reg_1306[5:0] <= 6'b000000;
    empty_20_reg_1311[5:0] <= 6'b111111;
    zext_ln209_1_reg_1361[15:4] <= 12'b000000000000;
    zext_ln700_reg_1366[31:16] <= 16'b0000000000000000;
    shl_ln_reg_1371[0] <= 1'b0;
    zext_ln67_reg_1376[0] <= 1'b0;
    zext_ln67_reg_1376[31:17] <= 15'b000000000000000;
    shl_ln67_1_reg_1410[0] <= 1'b0;
end

endmodule //load
